USE BD_COBROS

-- COMMIT TRANSACTION
-- ROLLBACK TRANSACTION

-- DATA CARGA DIARIA RAPIDTRAM 

CREATE TABLE #ESTADO (CIFCOD VARCHAR(250), PAGO_REALIZADO MONEY , ESTADO VARCHAR(250),FEC_ASIGNA DATE)

	 INSERT INTO #ESTADO (CIFCOD, PAGO_REALIZADO ,ESTADO, FEC_ASIGNA)
			SELECT CIFCOD, ISNULL([Pago realizado], 0) PAGO_REALIZADO, ESTADO, [FECHA DE ASIGNACION] FEC_ASIGNA
			FROM OPENROWSET(
			'Microsoft.ACE.OLEDB.12.0',
			'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_ESTADO.xlsx;HDR=YES',
			'SELECT * FROM [Sheet1$]') 


-- DATA DE ASIGNACION DIARIA ADM

CREATE TABLE #BASE_MONTOS (CIFCOD VARCHAR(250), 	  
						   CALIFICACION VARCHAR(10),CICLO VARCHAR(5), 
						   ESTADO2 VARCHAR(250))

     INSERT INTO #BASE_MONTOS (CIFCOD, CALIFICACION, CICLO ,ESTADO2)
			SELECT 
			CIFCOD,
			[Calificacion] CALIFICACION, 
			[Ciclo de corte] CICLO,
			[Indicador de acuerdo vigente] ESTADO2
			FROM OPENROWSET(
			'Microsoft.ACE.OLEDB.12.0',
			'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_ADM_MONTOS.xlsx;HDR=YES',
			'SELECT * FROM [Sheet1$]') WHERE [INDICADOR DE ACUERDO VIGENTE] <> 'REESTRUCTURACIÓN' -- EXCLUSION DE CUENTAS REESTRUCTURADAS
/*
SELECT NUM_PROOTR, SUM(VAL_DEPOSI) PAGO_REALIZADO
INTO #PAGOS
FROM BD_COBROS..PAGOS PP
JOIN DEUDOR D ON PP.COD_PRODUC = D.COD_PRODUC AND PP.COD_DEUDOR = D.COD_DEUDOR 
WHERE D.COD_PRODUC IN (4,19) AND FEC_DEPOSI >= '01-05-2025' AND D.MARCA = 'ADMINISTRATIVA'
GROUP BY NUM_PROOTR
*/

SELECT NULL COD_PRODUC, NULL COD_DEUDOR ,BM.CIFCOD, CALIFICACION, CICLO, ESTADO2, PAGO_REALIZADO, ESTADO, FEC_ASIGNA
INTO #BASE
FROM #BASE_MONTOS BM
JOIN #ESTADO E ON E.CIFCOD = BM.CIFCOD


	--ACTUALIZA CODIGOS DE CLIENTE
	UPDATE B
	SET B.COD_PRODUC = D.COD_PRODUC, B.COD_DEUDOR = D.COD_DEUDOR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.NUM_PROOTR = B.CIFCOD
	WHERE D.FEC_INGRES>='01-10-2024' --PRIMERA FECHA DE ASIGNACION CARTERA ADMINISTRATIVA -- NO CAMBIAR. 
	AND D.COD_PRODUC IN (4,19)
	AND D.MARCA='ADMINISTRATIVA'
	
	/*
UPDATE PP SET PP.PAGO_REALIZADO = B.PAGO_REALIZADO
FROM #BASE PP
JOIN #PAGOS B ON PP.CIFCOD = B.NUM_PROOTR
*/

--SELECT * FROM #BASE
	BEGIN TRANSACTION
	--ACTUALIZAR ESTADO DE COBRABILIDAD ADM EN ASIGNACIONES
	UPDATE A 
	SET A.FECHA_NC = D.FEC_ASIGNA,
	--SET A.CICLO = D.CICLO
	A.RANGO = D.ESTADO
	FROM BD_CARTERAS..Asignaciones A
	JOIN #BASE D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
	WHERE A.COD_PRODUC IN (4,19)
	AND A.FECHA_CARGA>= (SELECT CONVERT(VARCHAR(25),DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0),105))
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'

	
		--VALORES A ACTUALIZAR DATOS EN DEUDOR
	SELECT A.NUM_PRODUC,D.COD_PRODUC, D.COD_DEUDOR,
			D.MARCA2 ,CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 OR B.ESTADO <> 'MADURADO' THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END VENC, 
			CASE WHEN 
			         CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 THEN 0 
					 ELSE PAGO_MINIMO-PAGO_REALIZADO END < 0 OR B.ESTADO <> 'MADURADO' THEN 0 
					 ELSE (A.PAGO_MINIMO/A.PV)*(A.PV-2) END ABO_REF,
			A.PV, CASE WHEN (CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END) = 0 THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END VALPAGMIN_ACT , 
			A.PAGO_MINIMO, B.PAGO_REALIZADO, 
			--D.DIAS_VENCIDOS, B.DIAS_VENCIDOS, 
			--D.PV, B.PV , 
			D.MARCA_CAMPANIA, B.ESTADO,
			D.MARCA_JUICIO,   CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2) CALIFICACION, CAPITAL,S.NOM_USUARI EJECUTIVO, NOM_UBICA CATEGORIA, NOM_CATEGO DATO_RELEVANTE,
			(SELECT TOP 1 DIA.COD_GESTIO FROM DIARIO DIA
			WHERE DIA.COD_PRODUC = B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR AND DIA.SI_GESTION = 0 
			AND DIA.FEC_ULTMOD = (SELECT MAX(DI.FEC_ULTMOD) FROM DIARIO DI  
								WHERE DI.COD_PRODUC = B.COD_PRODUC AND DI.COD_DEUDOR = B.COD_DEUDOR AND DI.SI_GESTION = 0)
	    )GEST_AB
	INTO #ACT_MARCAS
	FROM #BASE B  
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	JOIN USUARIOS S ON D.COD_EJECUT = S.NUM_USUARI
	JOIN UBICADEU UD ON UD.COD_PRODUC = D.COD_PRODUC AND UD.COD_DEUDOR = D.COD_DEUDOR
	JOIN UBICACIO UB ON UB.COD_UBICA = UD.COD_UBICA
	JOIN CATEGORI CA ON CA.COD_CATEGO = D.COD_CATEGO 
	JOIN BD_CARTERAS..Asignaciones A ON A.NUM_PRODUC = D.NUM_PROOTR
	WHERE A.FECHA_CARGA>= (SELECT CONVERT(VARCHAR(25),DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0),105))
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'  

	-- OMITE MARCA ABO_REF DE CUENTAS QUE NO APLICAN REFINANCIAMIENTO - PROVISIONADAS - ARCHIVO ASIGNACION
	UPDATE #ACT_MARCAS SET ABO_REF = NULL
	FROM #ACT_MARCAS B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.SI_BLOQUE = 1 

	--BLOQUE DONDE ACTUALIZA MARCAS
	DECLARE @FECHA VARCHAR(12) = (SELECT 
    CAST(DAY(DATEADD(DAY, -1, GETDATE())) AS VARCHAR) + 
    UPPER(LEFT(DATENAME(MONTH, DATEADD(DAY, -1, GETDATE())), 3)))

	SELECT NUM_PROOTR,D.MARCA2, CONCAT(@FECHA,' VEN: $',VENC,' / ABO.REF: ',CASE WHEN ABO_REF IS NULL THEN 'NO APLICA' ELSE CAST(CONCAT(' $',ABO_REF) AS VARCHAR) END) ACTUALIZACION, VAL_PAGMIN , B.VALPAGMIN_ACT,PAGO_MINIMO,PAGO_REALIZADO,ESTADO
	FROM #ACT_MARCAS B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
	
	-- ACTUALIZA MARCAS
	UPDATE D SET MARCA2 =  CONCAT(@FECHA,' VEN: $',VENC,' / ABO.REF: ',CASE WHEN ABO_REF IS NULL THEN 'NO APLICA' ELSE CAST(CONCAT(' $',ABO_REF) AS VARCHAR) END), VAL_PAGMIN = B.VALPAGMIN_ACT,
	D.MARCA_CAMPANIA = B.ESTADO
	FROM #ACT_MARCAS B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 


--CUENTAS QUE ABONARON MÁS DEL 70% DE ABO_REF - BCO. PACIFICO ADMINISTRATIVA / REPORTE DE CUENTAS SE ENVIA LOS MARTES DE CADA SEMANA, CORREO AUTOMATICO. 

DECLARE @DIA VARCHAR(200) = CONVERT(VARCHAR,CAST(DATENAME(WEEKDAY,GETDATE()) AS VARCHAR))
--print @dia
IF @DIA <> 'Martes'
BEGIN
	PRINT 'CORREO NO ENVIADO'
END
ELSE
BEGIN
	DECLARE @ASUNTO VARCHAR(200) = 'CUENTAS QUE ABONARON MÁS DEL 70% DE ABO_REF - BCO. PACIFICO ADMINISTRATIVA'
	DECLARE @tablaHTML NVARCHAR(MAX);
		set	 @tablaHTML  =
						N'<html>
		<head>
		<style>
			body { font-family: Arial, sans-serif; font-size: 12px; }
			table { border-collapse: collapse; width: 90%; margin: auto; }
			th, td { border: 1px solid #000000; padding: 6px; text-align: center; }
			th { background-color: #000000; color: #ffc000; }
			p { font-size: 14px; }
		</style>
		</head>
		<body>
		<p>Buenos días/Tardes.<br>
		Estimados,</p>
		<p>El siguiente listado de clientes fue reportado en la última actualización con estado Madurado y realizaron pagos superiores al 70% del valor del ABO.REF.</p>
		<table>
			<tr>
				<th>CIFCOD</th>
				<th>COD_PRODUC</th>
				<th>COD_DEUDOR</th>
				<th>CAPITAL</th>
				<th>CALIFICACION</th>
				<th>ESTADO</th>
				<th>ABO_REF</th>
				<th>PAGO_MINIMO</th>
				<th>PAGO_REALIZADO</th>
				<th>FEC_PAGO</th>
				<th>DIFERENCIA</th>
				<th>EJECUTIVO</th>
				<th>CATEGORIA</th>
				<th>DATO_RELEVANTE</th>
				<th>GEST_AB</th>
			</tr>'+
			CAST((SELECT td=A.NUM_PRODUC,'', 
						 td=A.COD_PRODUC,'',
						 td=A.COD_DEUDOR,'', 
						 td=CAST(CAPITAL AS VARCHAR),'',
						 td=CALIFICACION,'',
						 td=ESTADO,'',
						 td=CAST(ABO_REF AS VARCHAR), '',
						 td=CAST(PAGO_MINIMO AS VARCHAR),'', 
						 td=CAST(PAGO_REALIZADO AS VARCHAR),'',
						 td=CAST(MAX(PP.FEC_DEPOSI) AS DATE),'',
						 td=CAST((PAGO_MINIMO-PAGO_REALIZADO)-20 AS varchar),'' ,
						 td=EJECUTIVO,'',
						 td=CATEGORIA,'',
						 td=DATO_RELEVANTE,'',
						 td=ISNULL(GEST_AB,'N/A'),''
			FROM #ACT_MARCAS A
			JOIN PAGOS PP ON PP.COD_PRODUC = A.COD_PRODUC AND A.COD_DEUDOR = PP.COD_DEUDOR
			WHERE ESTADO = 'MADURADO' AND PAGO_REALIZADO >= (ABO_REF*70/100) 
				  AND PP.FEC_DEPOSI >= (SELECT MAX(PA.FEC_DEPOSI) FROM PAGOS PA
										WHERE A.COD_PRODUC = PA.COD_PRODUC AND A.COD_DEUDOR = PA.COD_DEUDOR)

			GROUP BY NUM_PRODUC, A.COD_PRODUC, A.COD_DEUDOR, CAPITAL, CALIFICACION, ESTADO ,ABO_REF ,PAGO_MINIMO, 
			PAGO_REALIZADO,PP.FEC_DEPOSI ,EJECUTIVO, CATEGORIA ,DATO_RELEVANTE, GEST_AB
		 for xml raw('tr'), elements
						) as nvarchar(max)
						) + N'</table>	
						<br>
						<br>
						<p>Saludos cordiales,</p>	
					'+ -- CAMBIAR RUTA DE FIRMA 
						N'<body>'+
						N'<html>'

		EXEC msdb.dbo.sp_send_dbmail
			@profile_name = 'Procesos_EJR',
			@copy_recipients = '<mpinto@romerodyasociados.com>,<rdecimavilla1@romerodyasociados.com>', -- EDITAR CORREO EN CASO DE EJECUCION DE OTRO OPERATIVO
			@subject = @ASUNTO,
			@body = @tablaHTML,
			@body_format = 'HTML';
END	

    DROP TABLE #ACT_MARCAS
	DROP TABLE #BASE_MONTOS
	DROP TABLE #ESTADO
	DROP TABLE #BASE
