USE BD_COBROS
DECLARE @COD_PRODUC NVARCHAR(MAX) = '70' -- DEFINIR CODIGOS DEL PRODUCTO DE LA CAMPAÑA GESTIONADA DE < A >
DECLARE @ID_ESTRATEGIA NVARCHAR(MAX) = '16882'
DECLARE @FECHA DATE = CONVERT(NVARCHAR(20), GETDATE(),105)

DECLARE @TABLA_ESTRATEGIA TABLE(ID_ESTRATEGIA VARCHAR(10))
       INSERT INTO @TABLA_ESTRATEGIA 
       SELECT * FROM  Split(@ID_ESTRATEGIA,',') S	

--SELECT * FROM @TABLA_ESTRATEGIA

/* OBTENER CODIGOS DE CARTERA QUE SE ENVIAN POR PARAMETRO (@CARTERA) Y OBTENER LOS CODIGOS DE PRODUCTO RELACIONADOS A ESA CARTERA*/
       DECLARE @TABLAPRODUCTOS TABLE(COD_PRODUC TINYINT, NOM_PRODUC VARCHAR(50))
       INSERT INTO @TABLAPRODUCTOS
       SELECT DISTINCT C.COD_PRODUC, C.NOM_PRODUC
       FROM BD_COBROS.dbo.Split(@COD_PRODUC,',') S
       JOIN BD_COBROS.dbo.PRODUCTO C ON C.COD_PRODUC = S.splitdata 

--DECLARA EL GRUPO DE EJECUTIVOS QUE MANEJAN LA CAMPAÑA
DECLARE @CAMPANA VARCHAR(150) = CASE WHEN @COD_PRODUC = '70'  THEN 'COMPRADA'
								     WHEN @COD_PRODUC = '50,54,55'  THEN 'COMPRADA'
                                     WHEN @COD_PRODUC = '10'  THEN 'BOL'
									 WHEN @COD_PRODUC = '4,19' THEN 'ADM'
									 --WHEN @COD_PRODUC = '68' THEN 'CRECOS'
									 WHEN @COD_PRODUC = '68' THEN 'CONVENIOS'	 
									 ELSE 'REVISAR @COD_PRODUC' END
IF @CAMPANA = 'REVISAR @COD_PRODUC'
            PRINT @CAMPANA 

ELSE 

-- CREAR TABLA PARA INTRODUCIR DATOS DE LA CAMPAÑA GESTIONADA
CREATE TABLE #PREDICTIVO (
ID_ESTRATEGIA INT,
NOMBRE_ESTRATEGIA VARCHAR(50),
COD_PRODUC INT,  COD_DEUDOR INT, 
CODE_CLIENT VARCHAR (20),
CLIENTE VARCHAR (200),
PAIS VARCHAR(20),
TELEFONO VARCHAR (20),
ESTADO_GESTION VARCHAR (50),
FECHA_MARCACION VARCHAR (100),
STATUS_CALL VARCHAR (50),
ID_GRUPO INT, 
GRUPO VARCHAR (50),
ID_RESULTADO INT, 
RESULTADO VARCHAR (50),
ID_MOTIVO INT, 
MOTIVO VARCHAR (50),
USUARIO VARCHAR (100),
NUM_CEDRUC VARCHAR(50)
)

INSERT INTO #PREDICTIVO (ID_ESTRATEGIA, NOMBRE_ESTRATEGIA, CODE_CLIENT,	CLIENTE,	 PAIS,	TELEFONO,	ESTADO_GESTION	,FECHA_MARCACION,	STATUS_CALL,
ID_GRUPO,	GRUPO	,ID_RESULTADO,	RESULTADO,	ID_MOTIVO	,MOTIVO	,USUARIO
)
SELECT P.ID_ESTRATEGIA, NOMBRE_ESTRATEGIA, CODE_CLIENT,	CLIENTE, [CODIGO PAIS],	TELEFONO,	ESTADO_GESTION,	TRY_CONVERT(DATETIME, FECHA_MARCACION, 120) FECHA_MARCACION,	STATUS_CALL,	ID_GRUPO,
GRUPO	,ID_RESULTADO	,RESULTADO	,ID_MOTIVO	,MOTIVO	,USUARIO
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\CAMPANAS_PREDICTIVO\LIST_PREDICTIVO_BEEX.xlsx;HDR=YES',
	'SELECT * FROM [Sheet1$]') P
JOIN @TABLA_ESTRATEGIA TE ON TE.ID_ESTRATEGIA = P.ID_ESTRATEGIA
WHERE P.ID_ESTRATEGIA = TE.ID_ESTRATEGIA



SELECT * INTO #EJECUTIVOS	 
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\CAMPANAS_PREDICTIVO\EJECUTIVOS.xlsx;HDR=YES',
	'SELECT * FROM [Hoja1$]')
	 
-- ELIMINAR EJECUTIVOS QUE NO CORRESPONDEN A LA CAMPAÑA Y ASIGANR EL COD_EJECUT CORRESPONDIENTE
DELETE #EJECUTIVOS WHERE CAMPANA <> @CAMPANA
ALTER TABLE #EJECUTIVOS ADD COD_EJECUT INT


UPDATE EJ SET EJ.COD_EJECUT = G.NUM_USUARI
FROM #EJECUTIVOS EJ
JOIN BD_COBROS..GRUPOS G ON G.COD_USUARI = EJ.COD_USUARI

--SELECT * FROM #EJECUTIVOS

--SELECT * FROM #PREDICTIVO

UPDATE P SET P.CODE_CLIENT = CASE WHEN LEN(CODE_CLIENT) = 9 THEN '0'+CODE_CLIENT 
									WHEN LEN(CODE_CLIENT) = 10 THEN CODE_CLIENT
									WHEN LEN(CODE_CLIENT) = 12 THEN '0'+CODE_CLIENT
									ELSE CODE_CLIENT
									END FROM #PREDICTIVO P

UPDATE P SET P.TELEFONO = CASE WHEN LEN(TELEFONO) = 9 THEN '0'+TELEFONO
									ELSE TELEFONO
									END FROM #PREDICTIVO P



UPDATE PRE SET PRE.COD_DEUDOR = CLIE.COD_DEUDOR, PRE.COD_PRODUC = CLIE.COD_PRODUC
FROM #PREDICTIVO PRE
LEFT JOIN (
		SELECT DE.COD_PRODUC, DE.COD_DEUDOR, DE.NUM_CEDRUC,DE.VAL_SALDO, 
		ROW_NUMBER() OVER (PARTITION BY DE.NUM_CEDRUC ORDER BY DE.VAL_SALDO DESC) RANKIN 
		FROM #PREDICTIVO P
		JOIN BD_COBROS..DEUDOR DE ON DE.NUM_CEDRUC = P.CODE_CLIENT 
		JOIN @TABLAPRODUCTOS T ON T.COD_PRODUC = DE.COD_PRODUC
		JOIN BD_COBROS..SITUACIO S ON S.COD_SITUAC = DE.COD_SITUAC AND S.SI_CTAVIG = 1
		 ) CLIE ON CLIE.NUM_CEDRUC = PRE.CODE_CLIENT 
WHERE RANKIN = 1 

--ESTRATEGIA PROCESADA
SELECT P.*, E.NOM_USUARI FROM #PREDICTIVO P
LEFT JOIN #EJECUTIVOS E ON E.CODIGO = P.USUARIO

--CUENTAS NO TIPIFICADAS
SELECT PRD.ID_ESTRATEGIA ,PRD.NOMBRE_ESTRATEGIA ,P.NOM_PRODUC PRODUCTO, PRD.COD_DEUDOR, (SELECT TOP 1 D.COD_GESTIO FROM DIARIO D
			WHERE D.COD_PRODUC = PRD.COD_PRODUC AND D.COD_DEUDOR = PRD.COD_DEUDOR AND D.SI_GESTION = 0 
			AND D.FEC_ULTMOD = (SELECT MAX(DI.FEC_ULTMOD) FROM DIARIO DI  
								WHERE DI.COD_PRODUC = D.COD_PRODUC AND DI.COD_DEUDOR = D.COD_DEUDOR AND DI.SI_GESTION = 0)
	    )GEST_AB, PRD.CODE_CLIENT CEDULA, PRD.CLIENTE, PRD.TELEFONO, PRD.STATUS_CALL, PRD.RESULTADO, PRD.USUARIO, E.CAMPANA ,E.NOM_USUARI EJECUTIVO
FROM #PREDICTIVO PRD
JOIN #EJECUTIVOS E ON PRD.USUARIO = E.CODIGO
JOIN PRODUCTO P ON P.COD_PRODUC = PRD.COD_PRODUC
WHERE PRD.ESTADO_GESTION = 'Por gestionar' and PRD.USUARIO <> 'Predictivo'

DELETE FROM #PREDICTIVO WHERE STATUS_CALL in ('Sin Plan', 'marcando')
DELETE FROM #PREDICTIVO WHERE ESTADO_GESTION = 'Por gestionar' or ESTADO_GESTION = 'Existe CD'

-- CUENTAS QUE SE CARGARAN EN PLANCAMPAÑAS / SE CARGAN GESTIONES TIPIFICADAS EN LA HERRAMIENTA BEEX COMO "CON CONTACTO"

; WITH CTE AS (
		SELECT DISTINCT  P.COD_PRODUC , P.COD_DEUDOR, NUM_PRODUC, 'PRE.LIST+' +APE_DEUDOR APE_DEUDOR, NOM_DEUDOR, FEC_INGRES, NOM_SITUAC,
							'EJECUTIVO5' NOM_USUARI, 'EJECUTIVO5' NOM_EJECUT, 634 COD_EJECUT, UPPER(DATENAME(MONTH,GETDATE())) MES, 
							YEAR(GETDATE()) ANIO, CAST(GETDATE() AS DATE) FECDESDE, CAST(GETDATE() AS DATE)
 FECHASTA, PV, COD_AREA,	D.MARCA,NULL PV2,NULL CIUDAD, NULL CICLO, 
UPPER(DATENAME(MONTH,GETDATE())) + ' ' + CAST(DAY(GETDATE()) AS VARCHAR) OBSERVACION, 
CAST(DAY(GETDATE())AS VARCHAR) INDICE, 
1 PROCESADO, NULL CATEGORIA, D.VAL_SALDO, 
NULL FEC_GESTIO, CAST(FECHA_MARCACION AS DATETIME) HOR_GESTIO,NULL GESTION, NULL SEGUIMIENTO, 'G' TIPO, 2 MARCA2, 
UB.NOM_UBICA UBICACION, CAST(FECHA_MARCACION AS DATETIME) FEC_SIST,NULL FEC_ULTPAG, NULL ID_DIARIO,NULL COD_GESTIO,
ROW_NUMBER () OVER(PARTITION BY P.COD_PRODUC, P.COD_DEUDOR ORDER BY P.FECHA_MARCACION ) AS TT 

FROM #PREDICTIVO P
JOIN DEUDOR D ON P.COD_DEUDOR = D.COD_DEUDOR AND D.COD_PRODUC = P.COD_PRODUC
JOIN SITUACIO S ON D.COD_SITUAC = S.COD_SITUAC 
JOIN UBICADEU UD ON UD.COD_PRODUC = D.COD_PRODUC AND UD.COD_DEUDOR = D.COD_DEUDOR
JOIN UBICACIO UB ON UB.COD_UBICA = UD.COD_UBICA
WHERE P.ESTADO_GESTION = 'gestionado' AND P.USUARIO <> 'PREDICTIVO' AND GRUPO = 'CON CONTACTO' --AND D.MARCA = 'ADMINISTRATIVA'
)
SELECT * INTO #CARGAR_CPN FROM CTE WHERE TT=1

ALTER TABLE #CARGAR_CPN DROP COLUMN TT

-- SE BORRAN GESTIONES CON CONTACTO DEL REPORTE PARA LA INSERCION DE GESTIONES EN TBL_DIARIO 
DELETE FROM #PREDICTIVO WHERE ESTADO_GESTION = 'Gestionado' AND GRUPO = 'CON CONTACTO' AND  USUARIO <> 'Predictivo' 

-- REPORTE DE PLAN_CAMPAÑAS 
SELECT * FROM #CARGAR_CPN

-- INSERTAR EN PLANCAMPAÑAS CUENTAS GESTIONADAS POR EJECUTIVOS --

	
INSERT INTO PLANCAMPAÑAS (COD_PRODUC, COD_DEUDOR, NUM_PRODUC, APE_DEUDOR, NOM_DEUDOR, FEC_INGRES, NOM_SITUAC,
								NOM_USUARI, NOM_EJECUT, COD_EJECUT, MES, ANIO, FECDESDE, FECHASTA, PV, COD_AREA,
								MARCA, PV2, CIUDAD, CICLO, OBSERVACION, INDICE, PROCESADO, CATEGORIA, SALDO, 
								FEC_GESTIO, HORA,GESTION, SEGUIMIENTO, TIPO, MARCA2, UBICACION, FEC_SIST,FEC_ULTPAG, ID_DIARIO,COD_GESTIO)
	SELECT * FROM #CARGAR_CPN	
/*
delete FROM PLANCAMPAÑAS WHERE FECDESDE >= CAST(GETDATE() AS DATE) AND NOM_EJECUT = 'EJECUTIVO5' --AND COD_PRODUC IN (70)
*/

-- VERIFICAR GESTIONES 
UPDATE P SET P.NUM_CEDRUC = CODE_CLIENT
FROM #PREDICTIVO P

DELETE P FROM #PREDICTIVO P
WHERE
EXISTS (SELECT NUM_CEDRUC, PC.*
FROM BD_COBROS..PLANCAMPAÑAS PC 
JOIN BD_COBROS..DEUDOR D ON PC.COD_DEUDOR = D.COD_DEUDOR AND PC.COD_PRODUC = D.COD_PRODUC
JOIN @TABLAPRODUCTOS T ON T.COD_PRODUC = PC.COD_PRODUC
WHERE PC.FECDESDE >= @FECHA AND PROCESADO = 1
AND P.NUM_CEDRUC = D.NUM_CEDRUC) AND P.GRUPO = 'SIN CONTACTO'

SELECT *
INTO #REGISTROS_DIARIOS
FROM(
	SELECT P.*, ROW_NUMBER () OVER (PARTITION BY NUM_CEDRUC ORDER BY CASE WHEN USUARIO = 'Predictivo' THEN 2 ELSE 1 END ASC ) PRD
	FROM #PREDICTIVO P ) LES 
	WHERE PRD = 1

	--INSERTAR GESTIONES EN DIARIO

--INSERT INTO BD_COBROS..DIARIO (COD_PRODUC, COD_DEUDOR, FEC_GESTIO, COD_GESTIO, DES_GESTIO, DES_SEGUIM, FEC_SISTEM, USU_INGRES, USU_ULTMOD, FEC_ULTMOD, HORA_MOD, HOR_SISTEM, SI_GESTION, COD_CONTACT)
SELECT RS.COD_PRODUC,
	   RS.COD_DEUDOR,
	   CONVERT(VARCHAR(25),GETDATE(),105) AS FEC_GESTIO,
	   CASE WHEN USUARIO = 'Predictivo' THEN 'PRD'
               ELSE 'LD' END AS COD_GESTIO,
	    CASE WHEN RS.USUARIO IS NULL THEN 'LLAMADA MAQUINA' ELSE 'LLAMAR A CLIENTE' END AS DES_GESTIO,
	  CONVERT(VARCHAR(10), GETDATE(), 112) + ' SE REALIZA LLAMADA - NO SE TUVO RESPUESTA' AS DES_SEGIM,
	  GETDATE() AS FEC_SYSTEM,
	   824 AS USU_INGRES,
	   CASE WHEN USUARIO = 'Predictivo' THEN 824 ELSE EJE.COD_EJECUT END AS USU_ULTMOD,
	   CONVERT(DATETIME,RS.FECHA_MARCACION) AS FEC_ULTMOD,
	    CONVERT(DATETIME,RS.FECHA_MARCACION) AS HORA_MOD,
		CONVERT(DATETIME,RS.FECHA_MARCACION) AS HOR_SISTEM,
	   1 AS SI_GESTION,
	   ISNULL( E.COD_EST, 21)  AS COD_CONTACT

FROM #REGISTROS_DIARIOS RS
LEFT JOIN BD_COBROS..ESTADOS E ON E.NOM_EST = RS.RESULTADO AND E.TIP_EST = 'CTCLLAM'
JOIN BD_COBROS..DEUDOR D ON D.COD_DEUDOR = RS.COD_DEUDOR AND D.COD_PRODUC = RS.COD_PRODUC
LEFT JOIN #EJECUTIVOS EJE ON EJE.CODIGO = RS.USUARIO
JOIN SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
WHERE D.SI_RETIRA = 0 AND S.SI_CTAVIG = 1
--AND MARCA = 'ADMINISTRATIVA'


/*
-- INSERTAR NUMEROS MARCADOS EN EL PREDICTIVO AL DIARIO --

		SELECT	R.COD_PRODUC, R.COD_DEUDOR, R.COD_GESTIO, R.ID_REGISTRO, B.TELEFONO TELEFONO,
				'MSV.'+B.STATUS_CALL ESTADO, '000-'+U.COD_USUARI ORIGEN, SUBSTRING(CAST(newid() AS NVARCHAR(50)),1,30) UNIQUEID, CONVERT(DATETIME,FECHA_MARCACION) FECHA, CAST(NULL AS INT) ID_LLAMADA 
		INTO #REGISTROS_LLAMADAS
		FROM bd_cobros..DIARIO R 
		JOIN #PREDICTIVO B ON B.COD_PRODUC = R.COD_PRODUC AND B.COD_DEUDOR = R.COD_DEUDOR
		JOIN bd_cobros..USUARIOS U ON U.NUM_USUARI = R.USU_ULTMOD
		where r.fec_gestio = DATEADD(dd, DATEDIFF(dd,0, getdate()), 0) and r.cod_gestio in ('PRD','LD')
		and R.USU_INGRES = 824 
 
	SELECT * FROM #REGISTROS_LLAMADAS 
	--DROP TABLE #REGISTROS_LLAMADAS

		INSERT INTO BD_REPORTES.[dbo].[fpb_tb_ReporteLlamadasSalientes] (UNIQUEID,ORIGEN,STARTTIME,STOPTIME,DESTINO,ESTADO,FECHA)
		SELECT UNIQUEID, ORIGEN, FECHA, FECHA, TELEFONO, ESTADO, FECHA
		FROM #REGISTROS_LLAMADAS D

		INSERT INTO BD_REPORTES.[dbo].[fpb_tb_DiarioLlamadasSalientes] (UNIQUEID, ID_LLAMADA, ID_DIARIO, FECHA)
		SELECT R.UNIQUEID, D.ID_LLAMADA,R.ID_REGISTRO, R.FECHA
		FROM BD_REPORTES..[fpb_tb_ReporteLlamadasSalientes] D
		JOIN #REGISTROS_LLAMADAS R ON R.UNIQUEID = D.UNIQUEID-- AND R.ID_LLAMADA = D.ID_LLAMADA
		WHERE D.DESTINO = R.TELEFONO
				
	*/			
						


--SELECT * FROM #PREDICTIVO

