USE BD_COBROS
	
	SELECT * INTO #DEPURA
	FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\PROCESOS_MAPI\PLANTILLA_DEPURACION.xls;HDR=YES',
	'SELECT * FROM [Hoja1$]')

SELECT * FROM #DEPURA

BEGIN TRANSACTION 
UPDATE DI SET DI.DES_SEGUIM = CONCAT(DI.DES_SEGUIM,' MIN. A COBRAR $',DE.[VALOR A COBRAR],' CICLO: ',DE.[NUMERO DE CICLO],' FEC_ULT_PAG: ', CASE WHEN DE.FECHA_ULTIMO_PAGO IS NULL THEN 'NULL' ELSE DE.FECHA_ULTIMO_PAGO  END)
--SELECT DI.*
FROM DIARIO DI
JOIN DEUDOR D ON D.COD_PRODUC = DI.COD_PRODUC AND d.COD_DEUDOR = DI.COD_DEUDOR 
JOIN #DEPURA DE ON DE.CIFCOD = D.NUM_PROOTR
WHERE D.COD_PRODUC IN (4,19) AND D.MARCA = 'ADMINISTRATIVA' AND DI.COD_GESTIO = 'ACT' AND DI.FEC_GESTIO >= '01-04-2025' 

--COMMIT TRANSACTION 
