USE BD_COBROS



-- ESTE SCRIPT SE UTILIZA PARA ACTUALIZAR EL ACT EN LAS CUENTAS "REESTRUCTURACION"

SELECT * 
INTO #BASE
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\REPORTES\PROCESOS_MAPI\REVISAR2.xlsx;HDR=YES',
    'SELECT * FROM  [Hoja1$]')


SELECT CIFCOD, REGIONAL, [NUMERO DE CICLO], [CANTIDAD PAGOS VENCIDOS], [CAPITAL TOTAL] CAPITAL, [DEUDA TOTAL] TOT_DEUDA,	
       [PAGO MINIMO INICIAL] VENC_INI, [INDICADOR DE ACUERDO VIGENTE] MARCA, [VALOR A COBRAR] VALOR_COB 
INTO #BASE2
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\SALDOS\BDP_DATOS\BDP_ASIGNACION_ADM.xlsx;HDR=YES',
    'SELECT * FROM  [Hoja1$]')
WHERE [INDICADOR DE ACUERDO VIGENTE] = 'REESTRUCTURACIÓN'

UPDATE #BASE2 SET VALOR_COB = VALOR_COB +20 
FROM #BASE2
SELECT * FROM #BASE2


SELECT B.CIFCOD, D.COD_PRODUC, D.COD_DEUDOR , B2.CAPITAL, CAST(SUM([Total Pendiente]) AS MONEY ) DEUDA_TOTAL, '01-06-2025' FECHA,
B2.VALOR_COB,B2.MARCA
INTO #ACT
FROM DEUDOR D
JOIN #BASE B ON B.CIFCOD = D.NUM_PROOTR
JOIN #BASE2 B2 ON B2.CIFCOD = D.NUM_PROOTR
GROUP BY B.CIFCOD, D.COD_PRODUC, D.COD_DEUDOR , B2.CAPITAL, B2.VALOR_COB,B2.MARCA


UPDATE DI SET DES_SEGUIM = CONCAT('20250601 SE ACTUALIZA SALDO SEGÚN LISTADO DE CARTERA ENVIADO POR BANCO DEL PACIFICO AL 01/06/2025,',' CAPITAL: $',CAPITAL,' / DEUDA TOTAL: $',DEUDA_TOTAL,' - ',A.MARCA,' / VENC: $',VALOR_COB)   
FROM DIARIO DI
JOIN #ACT A ON A.COD_PRODUC = DI.COD_PRODUC AND DI.COD_DEUDOR = A.COD_DEUDOR
WHERE DI.COD_GESTIO = 'ACT' AND DI.FEC_GESTIO >= '01-06-2025'


