USE BD_COBROS

SELECT CIFCOD, REGIONAL, [NUMERO DE CICLO], [CANTIDAD PAGOS VENCIDOS] PV, [CAPITAL TOTAL] CAPITAL, [DEUDA TOTAL] TOT_DEUDA,	
       [PAGO MINIMO INICIAL] VENC_INI, [INDICADOR DE ACUERDO VIGENTE] MARCA, [VALOR A COBRAR] VALOR_COB 
INTO #BASE2
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\SALDOS\BDP_DATOS\BDP_ASIGNACION_ADM.xlsx;HDR=YES',
    'SELECT * FROM  [Hoja1$]') --ASIGNACION ADM EN RUTA SERVIDOR 2
WHERE [INDICADOR DE ACUERDO VIGENTE] <> 'REESTRUCTURACIÓN' -- CUENTAS DFP/NORMAL

--SUMA $20 AL VALOR PAGO MINIMO INICIAL
UPDATE #BASE2 SET VENC_INI = VENC_INI + 20 
FROM #BASE2 

--ACTUALIZACION GESTION ACT
UPDATE DI SET DES_SEGUIM = CONCAT('20250601 SE ACTUALIZA SALDO SEGÚN LISTADO DE CARTERA ENVIADO POR BANCO DEL PACIFICO AL 01/06/2025,',
' CAPITAL: $',B.CAPITAL,' DEUDA TOTAL: $',B.TOT_DEUDA,' VENC: $',B.VENC_INI,' ABO.REF: $',CAST((B.VENC_INI/B.PV)*(B.PV-2)AS VARCHAR))   
FROM DIARIO DI
JOIN DEUDOR D ON D.COD_PRODUC = DI.COD_PRODUC AND DI.COD_DEUDOR = D.COD_DEUDOR
JOIN #BASE2 B ON B.CIFCOD = D.NUM_PROOTR
WHERE DI.COD_GESTIO = 'ACT' AND DI.FEC_GESTIO >= '01-06-2025' 


