USE BD_COBROS

CREATE TABLE #BASE (COD_PRODUC INT, COD_DEUDOR INT, CIFCOD VARCHAR(250), PV INT, ESTADO VARCHAR(50) ,MONTO MONEY, CALIFICACION VARCHAR(10),CICLO VARCHAR(5), ESTADO2 VARCHAR(250),FEC_ASIGNA DATE)

	INSERT INTO #BASE (CIFCOD,  PV,MONTO, CALIFICACION,CICLO,ESTADO2) --, FEC_ASIGNA )
	SELECT CIFCOD,
	PV, 
	--ESTADO,
	VALOR_COB MONTO, 
	CALIFICACION, 
	[Numero de ciclo] CICLO, 
	MARCA ESTADO2
	--, [fecha de asignacion] FEC_ASIGNA
	FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\PROCESOS_MAPI\REVISAR.xlsx;HDR=YES',
	'SELECT * FROM [Hoja1$]') WHERE MARCA LIKE '%REES%'
	
	
	UPDATE #BASE SET MONTO = 0 WHERE MONTO IS NULL
	UPDATE #BASE SET PV = 0 WHERE PV IS NULL 
	UPDATE #BASE SET MONTO = MONTO + 20 WHERE MONTO>0 
	

	--ACTUALIZA CODIGOS DE CLIENTE
	UPDATE B
	SET B.COD_PRODUC = D.COD_PRODUC, B.COD_DEUDOR = D.COD_DEUDOR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.NUM_PROOTR = B.CIFCOD
	WHERE D.FEC_INGRES>='01-10-2024'
	AND D.COD_PRODUC IN (4,19)
	AND D.MARCA='ADMINISTRATIVA'
	
	SELECT * FROM #BASE

	--ACTUALIZAR ESTADO DE COBRABILIDAD ADM EN ASIGNACIONES
	BEGIN TRANSACTION
	UPDATE A 
	--SET A.FECHA_NC = D.FEC_ASIGNA
	--SET A.CICLO = D.CICLO
	--SET A.CPN_DSCTO = 0
	SET A.PV = D.PV
	FROM BD_CARTERAS..Asignaciones A
	JOIN #BASE D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
	WHERE A.COD_PRODUC IN (4,19)
	AND A.FECHA_CARGA >= '01-06-2025'
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'
	AND D.ESTADO2 LIKE '%REES%'

		--VALORES A ACTUALIZAR DATOS EN DEUDOR
	SELECT NUM_PROOTR,D.COD_PRODUC, D.COD_DEUDOR, MARCA,
		   D.MARCA2, '01JUN: VEN: $'+cast(B.MONTO as varchar) ACTUALIZACION,
		   D.VAL_PAGMIN, B.MONTO,
			--D.DIAS_VENCIDOS, B.DIAS_VENCIDOS, 
		  D.PV, B.PV , 
			--D.MARCA_CAMPANIA, B.ESTADO,
		  D.MARCA_JUICIO, CALIFICACION = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON CIFCOD = NUM_PROOTR -- D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
	AND  B.ESTADO2 LIKE '%REES%' AND B.ESTADO <> 'MADURADO'


	--ACTUALIZAR DATOS EN DEUDOR
	BEGIN TRANSACTION
	update D
	SET		--MARCA = 'ADMINISTRATIVA',
	         D.MARCA2 = '01JUN: VEN: $'+cast(B.MONTO as varchar) ,
			 D.VAL_PAGMIN = B.MONTO,
			--D.DIAS_VENCIDOS= B.DIAS_VENCIDOS, 
			  D.PV= B.PV , 
			--D.MARCA_CAMPANIA= B.ESTADO
	 	     D.MARCA_JUICIO = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON CIFCOD = NUM_PROOTR -- D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' AND  B.ESTADO2 LIKE '%REES%'	

--	COMMIT TRANSACTION
-- ROLLBACK TRANSACTION
