USE BD_COBROS

USE BD_COBROS
SELECT * 
INTO #NUEVA_ASIGNA
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\saldos\BDP_DATOS\BDP_ASIGNACION_ADM.xlsx;HDR=YES',
    'SELECT * FROM [Hoja1$]')

--SELECT * FROM #NUEVA_ASIGNA

SELECT D.NUM_PROOTR,COD_PRODUC, COD_DEUDOR,  N.[CAPITAL TOTAL], [DEUDA TOTAL], '01-06-2025' FROM DEUDOR D
JOIN #NUEVA_ASIGNA N ON N.CIFCOD = D.NUM_PROOTR 
WHERE NOT [INDICADOR DE ACUERDO VIGENTE] LIKE '%REES%'