USE BD_COBROS

CREATE TABLE #BASE (COD_PRODUC INT, 
                    COD_DEUDOR INT, 
					CIFCOD VARCHAR(250), 
					DIAS_VENCIDOS INT, 
					PV INT, 
					VNC_INI MONEY, 
					PAGO_REALIZADO MONEY , 
					ESTADO VARCHAR(250), 
					MINIMO_INI MONEY,
					CALIFICACION VARCHAR(10),
					CICLO VARCHAR(5), 
					ESTADO2 VARCHAR(250),
					FEC_ASIGNA DATE)

	INSERT INTO #BASE (CIFCOD, PAGO_REALIZADO ,ESTADO,
	--CALIFICACION,  
	FEC_ASIGNA--, CICLO,ESTADO2
	)
	SELECT CIFCOD, [Pago realizado] PAGO_REALIZADO, ESTADO,
	--[Calificacion] CALIFICACION,
	[FECHA DE ASIGNACION] FEC_ASIGNA
	--[Pago minimo inicial] MINIMO_INI,
	--[ciclo de corte] CICLO,
	--[Indicador de acuerdo vigente] ESTADO2
	--, ' ' FEC_ASIGNA
	FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_estado.xlsx;HDR=YES',
	'SELECT * FROM [Sheet1$]') --WHERE [INDICADOR DE ACUERDO VIGENTE] <> 'REESTRUCTURACIÓN'

	UPDATE B SET PAGO_REALIZADO = 0 FROM #BASE B
		                            WHERE PAGO_REALIZADO IS NULL

	--ACTUALIZA CODIGOS DE CLIENTE
	UPDATE B
	SET B.COD_PRODUC = D.COD_PRODUC, B.COD_DEUDOR = D.COD_DEUDOR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.NUM_PROOTR = B.CIFCOD
	WHERE D.FEC_INGRES>='01-10-2024'
	AND D.COD_PRODUC IN (4,19)
	AND D.MARCA='ADMINISTRATIVA'
	
	--SELECT * FROM #BASE WHERE VNC_INI <= PAGO_REALIZADO
	
	--ACTUALIZAR ESTADO DE COBRABILIDAD ADM EN ASIGNACIONES
	UPDATE A 
	SET A.FECHA_NC = D.FEC_ASIGNA,
	--SET A.CICLO = D.CICLO
	--SET 
	A.RANGO = D.ESTADO
	FROM BD_CARTERAS..Asignaciones A
	JOIN #BASE D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
	WHERE A.COD_PRODUC IN (4,19)
	AND A.FECHA_CARGA>='01-05-2025'
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'
	

	
		--VALORES A ACTUALIZAR DATOS EN DEUDOR
	SELECT A.NUM_PRODUC,D.COD_PRODUC, D.COD_DEUDOR,
			--D.MARCA2 ,CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 OR B.ESTADO <> 'MADURADO' THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END VENC, 
			--CASE WHEN CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END < 0 OR B.ESTADO <> 'MADURADO' THEN 0 ELSE (A.PAGO_MINIMO/A.PV)*(A.PV-2) END ABO_REF,
			--A.PV, CASE WHEN (CASE WHEN A.PAGO_MINIMO-B.PAGO_REALIZADO <=20 THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END) = 0 THEN 0 ELSE PAGO_MINIMO-PAGO_REALIZADO END VALPAGMIN_ACT , 
			--A.PAGO_MINIMO, B.PAGO_REALIZADO, 
			--D.DIAS_VENCIDOS, B.DIAS_VENCIDOS, 
			--D.PV, B.PV , 
			D.MARCA_CAMPANIA, B.ESTADO
			--D.MARCA_JUICIO, CALIFICACION = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	INTO #ACT_MARCAS
	FROM #BASE B  
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	JOIN BD_CARTERAS..Asignaciones A ON A.NUM_PRODUC = D.NUM_PROOTR
	WHERE A.FECHA_CARGA>='01-05-2025'
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'  
	
	SELECT * FROM #ACT_MARCAS B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
	AND D.MARCA_JUICIO <> CALIFICACION-- AND NUM_PROOTR = 'G37142' 


	SELECT NUM_PROOTR, D.MARCA_JUICIO, B.CALIFICACION
	--UPDATE D SET --D.MARCA_JUICIO = B.CALIFICACION
	      D.MARCA_CAMPANIA = B.ESTADO
	FROM #ACT_MARCAS B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' --AND NUM_PROOTR = 'K07657'
	 --AND VAL_PAGMIN <> B.VALPAGMIN_ACT

	/*
	--ACTUALIZAR DATOS EN DEUDOR
	BEGIN TRANSACTION
	update D
	SET		D.MARCA2 = '18ABR: VEN: $'+cast((B.VNC_INI-B.PAGO_REALIZADO) as varchar)+' / MIN: $'+cast((B.MINIMO_INI-PAGO_REALIZADO) as varchar)+'/ ABO.REF: $'+cast(((B.VNC_INI/B.PV)*(B.PV-2)) as varchar)
			--D.VAL_PAGMIN = B.VNC_INI, 
			--D.DIAS_VENCIDOS= B.DIAS_VENCIDOS, 
			--D.PV= B.PV , 
			--D.MARCA_CAMPANIA= B.ESTADO,
	 	    --D.MARCA_JUICIO = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' --AND D.MARCA_JUICIO LIKE '%REES%'
	--AND B.VNC_INI >0 
--	COMMIT TRANSACTION
-- ROLLBACK TRANSACTION
--DROP TABLE #ACT_MARCAS */