USE BD_COBROS
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION

-- DATA CARGA DIARIA RAPIDTRAM  - RECUPERACION DIARIA 

CREATE TABLE #ESTADO (CIFCOD VARCHAR(250), PAGO_REALIZADO MONEY , ESTADO VARCHAR(250),FEC_ASIGNA DATE)

	 INSERT INTO #ESTADO (CIFCOD, PAGO_REALIZADO ,ESTADO, FEC_ASIGNA)
			SELECT CIFCOD, ISNULL([Pago realizado],0) PAGO_REALIZADO, ESTADO, [FECHA DE ASIGNACION] FEC_ASIGNA
			FROM OPENROWSET(
			'Microsoft.ACE.OLEDB.12.0',
			'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_ESTADO.xlsx;HDR=YES',
			'SELECT * FROM [Sheet1$]') 

			--SELECT * FROM #ESTADO

-- DATA DE ASIGNACION DIARIA ADM

CREATE TABLE #BASE_MONTOS (CIFCOD VARCHAR(250),  MONTO MONEY,	  
						   CALIFICACION VARCHAR(10),CICLO VARCHAR(5),
						   ESTADO2 VARCHAR(250))

     INSERT INTO #BASE_MONTOS (CIFCOD, MONTO,CALIFICACION, CICLO ,ESTADO2)
			SELECT 
			CIFCOD, [Valor a cobrar] MONTO, 
			[Calificacion] CALIFICACION, 
			[Ciclo de corte] CICLO,
			[Indicador de acuerdo vigente] ESTADO2
			FROM OPENROWSET(
			'Microsoft.ACE.OLEDB.12.0',
			'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_ADM_MONTOS.xlsx;HDR=YES',
			'SELECT * FROM [Sheet1$]') WHERE [INDICADOR DE ACUERDO VIGENTE] IN  ('REESTRUCTURACIÓN','REESTRUCTURACION') -- EXCLUSION DE CUENTAS DFP / NORMAL


SELECT NULL COD_PRODUC, NULL COD_DEUDOR ,BM.CIFCOD, MONTO,CALIFICACION, CICLO, ESTADO2, PAGO_REALIZADO, ESTADO, FEC_ASIGNA
INTO #BASE
FROM #BASE_MONTOS BM
JOIN #ESTADO E ON E.CIFCOD = BM.CIFCOD
	
	UPDATE #BASE SET MONTO = 0 WHERE MONTO IS NULL
	--UPDATE #BASE SET PV = 0 WHERE PV IS NULL 
	UPDATE #BASE SET MONTO = MONTO + 20 WHERE MONTO>0 
	

	--ACTUALIZA CODIGOS DE CLIENTE
	UPDATE B
	SET B.COD_PRODUC = D.COD_PRODUC, B.COD_DEUDOR = D.COD_DEUDOR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.NUM_PROOTR = B.CIFCOD
	WHERE D.FEC_INGRES>='01-10-2024'
	AND D.COD_PRODUC IN (4,19)
	AND D.MARCA='ADMINISTRATIVA'
	
	--SELECT * FROM #BASE

	--ACTUALIZAR ESTADO DE COBRABILIDAD ADM EN ASIGNACIONES
	BEGIN TRANSACTION
	UPDATE A 
	SET A.FECHA_NC = D.FEC_ASIGNA,
	--SET A.CICLO = D.CICLO
	A.RANGO = D.ESTADO
	--SELECT *
	FROM BD_CARTERAS..Asignaciones A
	JOIN #BASE D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
	WHERE A.COD_PRODUC IN (4,19)
	AND A.FECHA_CARGA>='01-06-2025'
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'

		DECLARE @FECHA VARCHAR(12) = (SELECT 
    CAST(DAY(DATEADD(DAY, -1, GETDATE())) AS VARCHAR) + 
    UPPER(LEFT(DATENAME(MONTH, DATEADD(DAY, -1, GETDATE())), 3)))


		--VALORES A ACTUALIZAR DATOS EN DEUDOR
	SELECT NUM_PROOTR,D.COD_PRODUC, D.COD_DEUDOR,
		   D.MARCA2, @FECHA+' VEN: $'+cast(B.MONTO as varchar) ACTUALIZACION,
		   D.VAL_PAGMIN, B.MONTO,
			--D.DIAS_VENCIDOS, B.DIAS_VENCIDOS, 
			--D.PV, B.PV , 
			D.MARCA_CAMPANIA, B.ESTADO,
			D.MARCA_JUICIO,  CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2) CALIFICACION
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' AND SI_RETIRA = 0


	--ACTUALIZAR DATOS EN DEUDOR
	update D
	SET		D.MARCA2 = @FECHA+' VEN: $'+cast(B.MONTO as varchar),
			D.VAL_PAGMIN = B.MONTO,
			--D.DIAS_VENCIDOS= B.DIAS_VENCIDOS, 
			--D.PV= B.PV , 
			D.MARCA_CAMPANIA= B.ESTADO,
	 	    D.MARCA_JUICIO = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024'
