--ACTUALIZAR DIRECCION DE CUENTAS ADMINISTRATIVAS INGRESADAS CON VALORES NULL DESPUES DE QUE EL BCO. REPORTA LA INFORMACION
--INSERTAR EN LA RUTA ASIGNADA CIFCOD,DIRECCION TRABAJO, DIRECCION DOMICILIO
--ACTUALIZAR TODO LO QUE ESTE NULL, SD Y 0 EN SISTEMA, SI EL BCO. REPORTA INFORMACION NUEVA

USE BD_COBROS


SELECT * 
INTO #BASE
FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\REPORTES\PROCESOS_MAPI\REVISAR3.xlsx;HDR=YES',
    'SELECT * FROM  [Hoja1$]');

SELECT  * FROM #BASE

SELECT B.*, COD_PRODUC, COD_DEUDOR, DIR_DOMICI, DIR_TRABAJ
--UPDATE D SET DIR_TRABAJ = [DIRECCION TRABAJO]
FROM DEUDOR D
JOIN #BASE B ON D.NUM_PROOTR = B.CIFCOD
WHERE COD_PRODUC IN (4,19) AND MARCA = 'ADMINISTRATIVA' AND  SI_RETIRA = 0 AND DIR_TRABAJ = '0'