USE BD_COBROS

--COMMIT TRANSACTION
--ROLLBACK TRANSACTION
CREATE TABLE #BASE (COD_PRODUC INT, COD_DEUDOR INT, CIFCOD VARCHAR(250), PAGO_REALIZADO MONEY , ESTADO VARCHAR(250),CALIFICACION VARCHAR(10),CICLO VARCHAR(5), ESTADO2 VARCHAR(250),FEC_ASIGNA DATE)

	INSERT INTO #BASE (CIFCOD,PAGO_REALIZADO ,ESTADO,FEC_ASIGNA)
	SELECT
	CIFCOD,ISNULL([Pago realizado],0) PAGO_REALIZADO, ESTADO,
	--[Calificacion] CALIFICACION,[CICLO DE CORTE] CICLO, [Indicador de acuerdo vigente] ESTADO2, 
	[Fecha de asignacion] FEC_ASIGNA
	-- [Dias mora actualizado]  DIAS_VENCIDOS, [Cantidad Pagos Vencidos] PV, [Saldo vencido inicial] VNC_INI, 
	--[Pago minimo inicial] MINIMO_INI,
	
	FROM OPENROWSET(
	'Microsoft.ACE.OLEDB.12.0',
	'Excel 12.0;Database=C:\REPORTES\CARGA GESTION MASIVA\ACT_PACIFICO_ESTADO.xlsx;HDR=YES',
	'SELECT * FROM [Sheet1$]') WHERE ESTADO = 'RECUPERADO'
	
	UPDATE B
	SET B.COD_PRODUC = D.COD_PRODUC, B.COD_DEUDOR = D.COD_DEUDOR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.NUM_PROOTR = B.CIFCOD
	WHERE D.FEC_INGRES>='01-10-2024'
	AND D.COD_PRODUC IN (4,19)
	AND D.MARCA='ADMINISTRATIVA'
	
	BEGIN TRANSACTION
	--ACTUALIZAR ESTADO DE COBRABILIDAD ADM EN ASIGNACIONES
	UPDATE A 
	SET A.FECHA_NC = D.FEC_ASIGNA,
	--SET A.CICLO = D.CICLO
	    A.RANGO = D.ESTADO
	FROM BD_CARTERAS..Asignaciones A
	JOIN #BASE D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
	WHERE A.COD_PRODUC IN (4,19)
	AND A.FECHA_CARGA>=(SELECT CONVERT(VARCHAR(25),DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0),105))
	AND A.DESCRIPCION_ESTADO='ADMINISTRATIVA'

	/*
	SELECT D.COD_PRODUC, D.COD_DEUDOR,
			--D.MARCA2, '25ABR: VEN: $'+cast(B.MONTO as varchar) ACTUALIZACION,
			D.VAL_PAGMIN,
			--D.DIAS_VENCIDOS, B.DIAS_VENCIDOS, 
			--D.PV, B.PV , 
			D.MARCA_CAMPANIA, B.ESTADO
			--D.MARCA_JUICIO, CALIFICACION = CONCAT('C: ',B.CICLO,' - ',B.CALIFICACION,' - ',B.ESTADO2)
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
    AND NUM_PROOTR = 'H87640'
	*/

-- PARA VERIFICAR CUENTAS QUE CAMBIARON DE ESTADO MADURACION
    SELECT MARCA_CAMPANIA , ESTADO,MARCA2,MARCA2
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
	AND MARCA_CAMPANIA <> ESTADO
	
	-- PARA CUENTAS RECUPERADAS
	
	SELECT NUM_PROOTR, MARCA2,PAGO_REALIZADO, VAL_PAGMIN-20 VALOR_A_COBRAR, CASE WHEN PAGO_REALIZADO >= (VAL_PAGMIN-20) THEN 'COMPLETO' ELSE 'FALTA' END VRFIC, MARCA_CAMPANIA,ESTADO
	INTO #REPORTAR
	FROM #BASE B
	JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC =B.COD_PRODUC AND D.COD_DEUDOR = B.COD_DEUDOR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 

	SELECT * FROM #REPORTAR

	DECLARE @FECHA VARCHAR(12) = (SELECT 
    CAST(DAY(DATEADD(DAY, -1, GETDATE())) AS VARCHAR) + 
    UPPER(LEFT(DATENAME(MONTH, DATEADD(DAY, -1, GETDATE())), 3)))
	
	UPDATE D SET MARCA_CAMPANIA = ESTADO, VAL_PAGMIN = 0, D.DIAS_VENCIDOS = 0, MARCA2 = @FECHA+' VENC: $00.00'
	FROM  #REPORTAR R
	JOIN BD_COBROS..DEUDOR D ON R.NUM_PROOTR = D.NUM_PROOTR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES>='01-10-2024' 
	--AND d.MARCA_CAMPANIA <> ESTADO
	
	/*
	SELECT D.NUM_PROOTR CIFCOD, A.PAGO_MINIMO-20 VALOR_A_COBRAR ,PAGO_REALIZADO,CONCAT(APE_DEUDOR,' ',NOM_DEUDOR) CLIENTE, D.MARCA_CAMPANIA ,ESTADO,MARCA_JUICIO, MARCA2
	FROM  #REPORTAR R
	JOIN BD_COBROS..DEUDOR D ON R.NUM_PROOTR = D.NUM_PROOTR
	JOIN BD_CARTERAS..Asignaciones A ON A.NUM_PRODUC = R.NUM_PROOTR
	WHERE D.MARCA = 'ADMINISTRATIVA'
	AND D.FEC_INGRES >= '01-10-2024'
	AND A.FECHA_CARGA>='01-06-2025' 
    AND VRFIC = 'FALTA';
	*/
DECLARE @FEC DATE = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE);
DECLARE @ASUNTO VARCHAR(200) = CONCAT('ACTUALIZACION DE MARCAS - BCO. PACIFICO ADMINISTRATIVA AL ', CONVERT(VARCHAR(10), @FEC, 103));
DECLARE @tablaHTML NVARCHAR(MAX);

set	 @tablaHTML  =
				N'<html>
<head>
<style>
    body { font-family: Arial, sans-serif; font-size: 12px; }
	 p { font-size: 14px; }
</style>
</head>
<body>
<p>Buenos días/tardes.<br><br>
Estimados,<br>
Las marcas de la cartera administrativa fueron actualizadas al 
 <b>' + CONVERT(VARCHAR(10), @FEC, 103) + '</b>:</p>
				<p>Quedo atento a cualquier novedad. <br>
Saludos cordiales, 
</p>	
			<img src="F:\MAPI\CORREO\Sis-Matias Pinto1.png">'+
				N'<body>'+
				N'<html>';

EXEC msdb.dbo.sp_send_dbmail
    @profile_name = 'Procesos_EJR',
    @copy_recipients = '<rdecimavilla1@romerodyasociados.com>',
    @subject = @asunto,
    @body = @tablaHTML,
    @body_format = 'HTML';





