USE BD_COBROS

DECLARE @FEC_CARGA DATETIME SET @FEC_CARGA = '01-06-2025';		-- MODIFICAR FECHA POR INICIO DE MES
--RANGO FECHAS MES ACTUAL
DECLARE @FECPM DATETIME SET @FECPM = DATEADD(DAY, 1 - DAY(@FEC_CARGA), @FEC_CARGA);
DECLARE @FECUL DATETIME SET @FECUL = EOMONTH(@FEC_CARGA);
--RANGO FECHAS MES ANTERIOR
DECLARE @FECPMA DATETIME SET @FECPMA = DATEADD(MONTH, -1, @FECPM);
DECLARE @FECULA DATETIME SET @FECULA = DATEADD(DAY, -1, @FECPM);


select 
	CASE WHEN a.COD_PRODUC=4 THEN 'VISA' ELSE 'MASTERCARD' END AS PRODUCTO,
	a.COD_PRODUC, a.COD_DEUDOR, d.NUM_PROOTR, d.NUM_CEDRUC, 
	a.[NOMBRE_CLIENTE ] , d.VAL_SALCAP, d.VAL_SALDO, a.DIAS_VENCIDOS, d.FEC_SITUAC, 
	 CASE WHEN B.CPN_DSCTO = 1 THEN 'DFP'
	     WHEN B.CPN_DSCTO = 2 THEN 'NORMAL'
		 ELSE 'REESTRUCTURACIÓN' END INDIC_ACUERDO_VGNT_ANT, 
	CASE WHEN A.CPN_DSCTO = 1 THEN 'DFP'
	     WHEN A.CPN_DSCTO = 2 THEN 'NORMAL'
		 ELSE 'REESTRUCTURACIÓN' END INDIC_ACUERDO_VGNT_ACT
	,s.NOM_SITUAC,UB.NOM_UBICA AS CATEGORIA, DR.NOM_CATEGO AS DATO_RELEVANTE,
	U.NOM_USUARI AS EJECUT, G.GRUPO AS GRUP,
	B.CAPITAL CAP_B_ANT, A.CAPITAL CAP_B_ACT, 
	B.TOTAL TOT_B_ANT, A.TOTAL TOT_B_ACT, 
	(SELECT MAX(FEC_PAGO) FROM BD_COBROS..PAGOS AS PA1 WHERE PA1.EST_PAGO = 3 AND PA1.COD_PRODUC = D.COD_PRODUC
    AND PA1.COD_DEUDOR = D.COD_DEUDOR) AS ULT_PAG,

	(SELECT SUM(PP.VAL_DEPOSI) FROM BD_COBROS..PAGOS AS PP
		WHERE D.COD_PRODUC=PP.COD_PRODUC AND D.COD_DEUDOR=PP.COD_DEUDOR AND
		PP.EST_PAGO=3 AND PP.FEC_DEPOSI>=@FECPMA AND PP.FEC_DEPOSI<=@FECULA) AS PAG_MES_ANT,
	(SELECT SUM(PP.VAL_DEPOSI) FROM BD_COBROS..PAGOS AS PP
		WHERE D.COD_PRODUC=PP.COD_PRODUC AND D.COD_DEUDOR=PP.COD_DEUDOR AND
		PP.EST_PAGO=3 AND PP.FEC_DEPOSI>=@FECPM AND PP.FEC_DEPOSI<=@FECUL) AS PAG_MES_ACT,

	'NULL' GES_AB, 'NULL' GES_CBP, d.MARCA, d.MARCA_CAMPANIA
, 
	--convert(varchar(10),D.FEC_INGRES,103) as FEC_INGRES ,UB.NOM_UBICA AS UBICACION,
	--U.COD_USUARI AS EJECUT, G.GRUPO AS GRUP, G.GRUGEST, DR.NOM_CATEGO AS SUB_CATEGO,

	a.DESCRIPCION_ESTADO EST_MES_ACT, b.DESCRIPCION_ESTADO EST_MES_ANT, CAST(0.00 AS MONEY) DIFERENCIA_CAP, CAST(0.00 AS MONEY) DIFERENCIA_TOT,
	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' OBS_EJR,
	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' OBS_BANCO

INTO #BASE_CARTERAS_MES
from BD_CARTERAS..Asignaciones a 

left join BD_CARTERAS..Asignaciones b on a.COD_PRODUC=b.COD_PRODUC and a.COD_DEUDOR =b.COD_DEUDOR
	and b.FECHA_CARGA between @FECPMA and @FECULA and a.COD_PRODUC in (4,19) AND A.DESCRIPCION_ESTADO = 'ADMINISTRATIVA'
left join BD_COBROS..DEUDOR d on d.COD_PRODUC=a.COD_PRODUC and d.COD_DEUDOR =a.COD_DEUDOR
       LEFT JOIN BD_COBROS..CATEGORI DR ON DR.COD_CATEGO = D.COD_CATEGO
       LEFT JOIN BD_COBROS..SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
       LEFT JOIN BD_COBROS..GRUPOS G ON G.NUM_USUARI = D.COD_EJECUT
       LEFT JOIN BD_COBROS..USUARIOS U ON U.NUM_USUARI = D.COD_EJECUT
       LEFT JOIN BD_COBROS..UBICADEU C ON C.COD_PRODUC = D.COD_PRODUC AND C.COD_DEUDOR = D.COD_DEUDOR
       LEFT JOIN BD_COBROS..UBICACIO UB ON UB.COD_UBICA = C.COD_UBICA
where a.FECHA_CARGA between @FECPM and @FECUL and a.COD_PRODUC in (4,19) AND A.DESCRIPCION_ESTADO = 'ADMINISTRATIVA'


UPDATE A SET A.GES_AB = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR AND B.SI_GESTION=0 
        
UPDATE A SET A.GES_AB = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR AND B.SI_GESTION=0 
	AND COD_GESTIO<>'ZZ' AND COD_GESTIO<>'LD' AND COD_GESTIO<>'CN' AND COD_GESTIO<>'BD' AND COD_GESTIO<>'PL' AND COD_GESTIO<>'CV' AND COD_GESTIO<>'LIQ1' AND COD_GESTIO<>'CA1'

UPDATE A SET A.GES_AB = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR AND B.SI_GESTION=0 
	AND COD_GESTIO='PM'

UPDATE A SET A.GES_CBP = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR
	AND COD_GESTIO IN ('CBP','RPL')

UPDATE A SET A.OBS_EJR='', OBS_BANCO=''  FROM #BASE_CARTERAS_MES A

UPDATE A SET A.PAG_MES_ANT=0.00 FROM #BASE_CARTERAS_MES A WHERE PAG_MES_ANT IS NULL
UPDATE A SET A.PAG_MES_ACT=0.00 FROM #BASE_CARTERAS_MES A WHERE PAG_MES_ACT IS NULL


UPDATE A SET A.DIFERENCIA_CAP=CAP_B_ACT+PAG_MES_ANT-CAP_B_ANT, 
			A.DIFERENCIA_TOT=TOT_B_ACT+PAG_MES_ANT-TOT_B_ANT
			FROM #BASE_CARTERAS_MES A

--- PARA REVISION DE SALDOS 

UPDATE A SET A.OBS_EJR = (CASe 
    WHEN TOT_B_ACT < CAP_B_ACT THEN 'CAPITAL MAYOR A SALDO TOTAL'
	when DIFERENCIA_CAP=0  then 'SIN NOVEDAD'
	WHEN CAP_B_ANT<=0 AND DIFERENCIA_TOT=0 then 'CAPITAL CERO SIN NOVEDAD EN TOTAL'
	WHEN PAG_MES_ANT>0 AND DIFERENCIA_TOT BETWEEN -10 AND 10 then 'VARIACION DISCRETA CON PAGO'
	WHEN DIFERENCIA_TOT BETWEEN -10 AND 10 then 'VARIACION DISCRETA SIN PAGO'
	WHEN EST_MES_ANT='LEGAL' AND PAG_MES_ANT>0 AND DIFERENCIA_TOT BETWEEN -9999 AND 9999 then 'VARIACION STATUS LEGAL CON PAGO'
	WHEN EST_MES_ANT='LEGAL' AND EST_MES_ACT='CASTIGO' then 'VARIACION POR CAMBIO DE STATUS'
	WHEN DIFERENCIA_CAP IS NULL then 'CUENTA NUEVA'
	ELSE '' END)
FROM #BASE_CARTERAS_MES A

-- 0. TODAS LOS CLIENTES ASIGNADOS EN EL MES 
SELECT * FROM #BASE_CARTERAS_MES 
/*
-- 1. CUENTAS SALDOS CON DIFERENCIAS - ACTUALZAR
SELECT PRODUCTO,	COD_PRODUC,	COD_DEUDOR,	CAP_FECH=CAP_B_ACT-PAG_MES_ACT,	TOT_FECH=TOT_B_ACT-PAG_MES_ACT,	FECHA_HOY=GETDATE(), 
CASE WHEN (VAL_SALDO-(TOT_B_ACT-PAG_MES_ACT))>=50 THEN 'ALTO' 
WHEN (VAL_SALDO-(TOT_B_ACT-PAG_MES_ACT))>=0 THEN 'OK'  ELSE 'REV' END AS ESTADO , 	
NUM_CEDRUC,	[NOMBRE_CLIENTE ],VAL_SALCAP, 	 VAL_SALDO, 	DIFE=VAL_SALDO-(TOT_B_ACT-PAG_MES_ACT),
NOM_SITUAC,	CATEGORIA,	EJECUT,	GRUP,	CAP_B_ACT,	TOT_B_ACT,	PAG_MES_ACT, ULT_PAG
FROM #BASE_CARTERAS_MES 
WHERE (CASE WHEN (VAL_SALDO-(TOT_B_ACT-PAG_MES_ACT))>=50 THEN 'ALTO' 
	WHEN (VAL_SALDO-(TOT_B_ACT-PAG_MES_ACT))>=0 THEN 'OK'  ELSE 'REV' END) IN ('REV','ALTO')

-- 2. PARA ENVIO DE CONSULTAS DE DIFERENCIAS DE SALDOS (CORREO BANCO)
SELECT PRODUCTO, NUM_PROOTR	,NUM_CEDRUC,	[NOMBRE_CLIENTE ], 	 CAP_B_ANT CAPITAL_ANTERIOR, 	 CAP_B_ACT CAPITAL_ACTUAL,
TOT_B_ANT AS TOTAL_ANTERIOR, 	TOT_B_ACT TOTAL_ACTUAL, 	 DIFERENCIA_TOT DIFERENCIA, 	
CASE WHEN PAG_MES_ANT>1000 THEN 'PAGO ALTO - NO CONSULTAR'
	WHEN DIFERENCIA_TOT<=0 THEN 'DISMINUCIÓN DE SALDO'
	WHEN DIFERENCIA_TOT>0 THEN 'INCREMENTO DE SALDO'
	ELSE '' END OBS_EJR,	OBS_BANCO,
PAG_MES_ANT
FROM #BASE_CARTERAS_MES
WHERE OBS_EJR=''
*/
-- 3. CLIENTES CON CAMBIOS STATUS ( DE VENCIDA A CASTIGO)
SELECT PRODUCTO, NUM_PROOTR	,COD_PRODUC,	COD_DEUDOR,	[NOMBRE_CLIENTE ], 	VAL_SALDO,	FEC_SITUAC,	NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,
	EJECUT,	GRUP,	ULT_PAG,	GES_AB,	MARCA, MARCA_CAMPANIA,INDIC_ACUERDO_VGNT_ANT, INDIC_ACUERDO_VGNT_ACT
FROM #BASE_CARTERAS_MES
WHERE INDIC_ACUERDO_VGNT_ANT <> INDIC_ACUERDO_VGNT_ACT AND OBS_EJR <> 'CUENTA NUEVA'

-- 5. REVISION DE CUENTAS EN VERIFICAR SALDOS / CONSULTA BANCO (CIENTES CANCELADOS CON INCREMENTO DE SALDOS)
SELECT PRODUCTO,	NUM_PROOTR CIFCOD, COD_DEUDOR	,[NOMBRE_CLIENTE ], 	TOT_B_ANT AS TOTAL_ANTERIOR,PAG_MES_ANT, CAP_B_ACT CAPITAL_ACTUAL, TOT_B_ACT TOTAL_ACTUAL,	FEC_SITUAC,	NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,
	EJECUT,	GRUP,	ULT_PAG,	GES_AB,	EST_MES_ACT ACTUAL_SEGMENTO,	EST_MES_ANT ANTERIOR_SEG, GES_CBP
FROM #BASE_CARTERAS_MES
WHERE NOM_SITUAC IN ('VERIF.SALDO(AC.CANC)','VERIFICAR SALDO(N/C)') AND ULT_PAG<'01-05-2025' AND GES_CBP='NULL' -- PONER MES ACTUAL

-- 6. CUENTAS CANCELADAS SIN PM ASIGNADO (REPORTE COBRANZAS)
SELECT PRODUCTO,	COD_PRODUC,	COD_DEUDOR,	[NOMBRE_CLIENTE ], 	TOT_B_ANT AS TOTAL_ANTERIOR, TOT_B_ACT TOTAL_ACTUAL,	FEC_SITUAC,	NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,
	EJECUT,	GRUP,	ULT_PAG,	GES_AB,	EST_MES_ACT ACTUAL_SEGMENTO,	EST_MES_ANT ANTERIOR_SEG, GES_CBP
FROM #BASE_CARTERAS_MES
WHERE NOT NOM_SITUAC IN ('VERIF.SALDO(AC.CANC)','VERIFICAR SALDO(N/C)') 
	AND  DATO_RELEVANTE='CANCELADA' AND GES_AB<>'PM'

-- 7. CUENTAS RETORNADAS (CUENTA CERRADA)
SELECT PRODUCTO, NUM_PRODUC	,A.COD_PRODUC,	A.COD_DEUDOR,	[NOMBRE_CLIENTE ], 	TOT_B_ANT AS TOTAL_ANTERIOR, TOT_B_ACT TOTAL_ACTUAL,	A.FEC_SITUAC,	NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,
	EJECUT,	GRUP,	ULT_PAG,	GES_AB,	EST_MES_ACT ACTUAL_SEGMENTO, PV	,CASE WHEN MARCA_JUICIO LIKE '%REES%' THEN 'REESTRUCTURACION'
			      WHEN MARCA_JUICIO LIKE '%NORMA%' THEN 'NORMAL'
				  WHEN MARCA_JUICIO LIKE '%DFP%'THEN 'DFP'
				  ELSE '' END [IND.REES.VGNTE], D.VAL_PAGMIN ,EST_MES_ANT ANTERIOR_SEG, GES_CBP
FROM #BASE_CARTERAS_MES A
join BD_COBROS..DEUDOR d on d.COD_PRODUC=a.COD_PRODUC and d.COD_DEUDOR =a.COD_DEUDOR
WHERE NOM_SITUAC IN ('CUENTA CERRADA') 

--DROP TABLE #BASE_CARTERAS_MES