USE BD_COBROS
CREATE TABLE #TABLAPAGOS (
    COD_DEUDOR INT,
    COD_PRODUC INT,
    PAGO NVARCHAR(10),
    FECHA_PAGO DATE,	
    NOM_EJECUT NVARCHAR(30)
);
	
--INGRESAR ACTUALIZACION DE DATOS DE PAGO
DECLARE @COD_DEUDOR INT = 90034
DECLARE @COD_PRODUC INT =	19
DECLARE @FECHA_PAGO VARCHAR(20) = '02-06-2025' 
DECLARE @NOM_EJECUT VARCHAR(30) = 'EJECUTIVO PAGO' -- NUEVO EJECUTIVO A ASIGNAR EL PAGO

INSERT INTO #TABLAPAGOS (COD_DEUDOR, COD_PRODUC, FECHA_PAGO, NOM_EJECUT)
VALUES (@COD_DEUDOR, @COD_PRODUC, CONVERT(DATE, @FECHA_PAGO, 105), @NOM_EJECUT)

 --CONFIRMAR TRASACCION--
	--COMMIT TRANSACTION;

-- REVERTIR TRASACCION--
	--ROLLBACK TRANSACTION;

-- ASIGNAR MAS PAGOS
/*
INSERT INTO #TABLAPAGOS (COD_DEUDOR, COD_PRODUC, FECHA_PAGO, NOM_EJECUT)
VALUES (90322, 10, CONVERT(DATE, '04-04-2025', 105), 'GEOVANA SUAREZ')--, (12827, 70, '157.73', CONVERT(DATE, '-11-2024', 105), 'JANIKEE ESPIN');
*/

--SELECT * FROM #TABLAPAGOS

---VERIFICAR LOS CAMBIOS A REALIZAR
SELECT PR.NOM_PRODUC PRODUCTO, PA.COD_PRODUC, PA.COD_DEUDOR, D.NOM_DEUDOR + ' ' + D.APE_DEUDOR CLIENTE ,G.NOM_USUARI EJECUT_ACTUAL, 
       TP.NOM_EJECUT , PA.COD_EJECUT CODIGO_EJECUT_ACT, U.NUM_USUARI COD_EJECUT_NUEVO, PA.VAL_PAGO ULT_PAG, TP.FECHA_PAGO, CAST(PA.FEC_DEPOSI AS DATE) FEC_DEPOSI
INTO #COMP_PAGO
FROM PAGOS PA 
JOIN #TABLAPAGOS TP ON TP.COD_DEUDOR = PA.COD_DEUDOR AND TP.COD_PRODUC = PA.COD_PRODUC
JOIN DEUDOR D ON D.COD_DEUDOR = PA.COD_DEUDOR AND D.COD_PRODUC = PA.COD_PRODUC
LEFT JOIN GRUPOS G ON G.NUM_USUARI = PA.COD_EJECUT
JOIN BD_COBROS..USUARIOS U ON U.NOM_USUARI = TP.NOM_EJECUT
JOIN PRODUCTO PR ON PR.COD_PRODUC = PA.COD_PRODUC
WHERE  FEC_DEPOSI = TP.FECHA_PAGO AND EST_PAGO = 3
			
SELECT * FROM #COMP_PAGO

--TRANSACCION EN PROCESO

BEGIN TRANSACTION
    
UPDATE PP SET PP.COD_EJECUT = SP.COD_EJECUT_NUEVO, TIP_AUDIT = 3 
FROM PAGOS PP
JOIN #COMP_PAGO SP ON  PP.COD_PRODUC = SP.COD_PRODUC AND PP.COD_DEUDOR = SP.COD_DEUDOR
JOIN BD_COBROS..PRODUCTO PR ON SP.COD_PRODUC=PR.COD_PRODUC
JOIN BD_COBROS..USUARIOS U ON PP.COD_EJECUT=U.NUM_USUARI
JOIN BD_COBROS..DEUDOR D ON PP.COD_PRODUC=D.COD_PRODUC AND PP.COD_DEUDOR=D.COD_DEUDOR 
WHERE PP.FEC_DEPOSI = SP.FEC_DEPOSI --AND PP.COD_FORPAG = 'CC'

 
SELECT NOM_PRODUC PRODUCTO, D.COD_DEUDOR ,D.APE_DEUDOR + ' ' + D.NOM_DEUDOR CLIENTE ,NOM_USUARI EJECUTIVO_NUEVO, CAST(PP.FEC_DEPOSI AS DATE) FEC_PAGO, CONCAT('$ ',PP.VAL_DEPOSI) PAGO FROM PAGOS PP
JOIN #TABLAPAGOS SP ON  PP.COD_PRODUC = SP.COD_PRODUC AND PP.COD_DEUDOR = SP.COD_DEUDOR
JOIN BD_COBROS..PRODUCTO PR ON PP.COD_PRODUC=PR.COD_PRODUC
JOIN BD_COBROS..USUARIOS U ON PP.COD_EJECUT=U.NUM_USUARI
JOIN BD_COBROS..DEUDOR D ON PP.COD_PRODUC=D.COD_PRODUC AND PP.COD_DEUDOR=D.COD_DEUDOR 
WHERE PP.FEC_DEPOSI = SP.FECHA_PAGO
	
