SELECT * 
FROM BD_CARTERAS..Asignaciones A
--JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
WHERE A.FECHA_CARGA >= '01-06-2025' AND A.COD_PRODUC IN (4,19) AND A.DESCRIPCION_ESTADO = 'ADMINISTRATIVA'


SELECT NUM_PROOTR,COD_PRODUC, COD_DEUDOR ,CASE WHEN MARCA_JUICIO LIKE '%REES%' THEN 0
			      WHEN MARCA_JUICIO LIKE '%NORMA%' THEN 1
				  WHEN MARCA_JUICIO LIKE '%DFP%'THEN 2
				  ELSE '' END INDICADOR
INTO #ACT_CART
FROM BD_COBROS..DEUDOR D
WHERE D.COD_PRODUC IN (4,19) AND D.MARCA = 'ADMINISTRATIVA' AND SI_RETIRA = 0


SELECT D.NUM_PROOTR, A.COD_PRODUC, A.COD_DEUDOR,CASE WHEN CPN_DSCTO = 1 THEN 'DFP'
	     WHEN CPN_DSCTO = 2 THEN 'NORMAL'
		 ELSE 'REESTRUCTURACIÓN' END INDIC_ACUERDO_VGNT_ASIGNACION, CASE WHEN INDICADOR = 1 THEN 'DFP'
	     WHEN INDICADOR = 2 THEN 'NORMAL'
		 ELSE 'REESTRUCTURACIÓN' END INDIC_ACUERDO_VGNT_ACT
INTO #CAMB
FROM BD_CARTERAS..Asignaciones A
JOIN #ACT_CART D ON D.COD_PRODUC = A.COD_PRODUC AND D.COD_DEUDOR = A.COD_DEUDOR
WHERE A.FECHA_CARGA >= '01-06-2025'
AND CAST(CPN_DSCTO AS INT) <> INDICADOR AND INDICADOR = 0

SELECT NUM_PROOTR, C.COD_PRODUC, C.COD_DEUDOR, C.INDIC_ACUERDO_VGNT_ASIGNACION, C.INDIC_ACUERDO_VGNT_ACT, ISNULL(SUM(PP.VAL_DEPOSI),0) PAGADO  FROM #CAMB C
LEFT JOIN BD_COBROS..PAGOS PP ON C.COD_PRODUC = PP.COD_PRODUC AND C.COD_DEUDOR = PP.COD_DEUDOR
GROUP BY NUM_PROOTR, C.COD_PRODUC, C.COD_DEUDOR, C.INDIC_ACUERDO_VGNT_ASIGNACION, C.INDIC_ACUERDO_VGNT_ACT

