USE BD_COBROS
DECLARE @COD_PRODUC NVARCHAR(MAX) = '4,19'

/* OBTENER CODIGOS DE CARTERA QUE SE ENVIAN POR PARAMETRO (@CARTERA) Y OBTENER LOS CODIGOS DE PRODUCTO RELACIONADOS A ESA CARTERA*/
       DECLARE @TABLAPRODUCTOS TABLE(COD_PRODUC TINYINT, NOM_PRODUC VARCHAR(50))
       INSERT INTO @TABLAPRODUCTOS
       SELECT DISTINCT C.COD_PRODUC, C.NOM_PRODUC
       FROM BD_COBROS.dbo.Split(@COD_PRODUC,',') S
       JOIN BD_COBROS.dbo.PRODUCTO C ON C.COD_PRODUC = S.splitdata 
       
--Extraer información de IVR's enviados
CREATE TABLE #IVR_BEEX(
CODE_CLIENT NVARCHAR(15),
TELEFONO NVARCHAR(15),
STATUS_CALL NVARCHAR(50),
FECHA_MARCACION DATETIME
)
CREATE TABLE #LLAMADAS_BEEX(
EMPRESA NVARCHAR(250),
CAMPANA NVARCHAR(250),
TIPO_LLAMADA NVARCHAR(100),
TIPO_MARCACION NVARCHAR(100),
TELEFONO NVARCHAR(100),
RESULTADO NVARCHAR(100),
FECHA_INI DATETIME, 
FECHA_FIN DATETIME,
ID_USUARIO INT, 
USUARIO NVARCHAR(100),
TIEMPO_TOTAL INT, 
TIEMPO_HABLADO INT, 
WEB NVARCHAR(100),
ID_LLAMADA VARCHAR(100),
ENCUESTA NVARCHAR(100),
DURACION DATETIME
)
INSERT INTO #IVR_BEEX
SELECT CODE_CLIENT,  TELEFONO, STATUS_CALL, FECHA_MARCACION
FROM OPENROWSET(
       'Microsoft.ACE.OLEDB.12.0',
       'Excel 12.0;Database=C:\REPORTES\CAMPANAS_IVR\GESTIONES_IVR_BEEX.xlsx;HDR=YES',
       'SELECT * FROM [Hoja1$]')
WHERE STATUS_CALL <> '' 

INSERT INTO #LLAMADAS_BEEX (EMPRESA ,CAMPANA,TIPO_LLAMADA,TIPO_MARCACION ,TELEFONO ,RESULTADO ,FECHA_INI , 
							FECHA_FIN ,ID_USUARIO , USUARIO ,TIEMPO_TOTAL , TIEMPO_HABLADO , WEB ,ID_LLAMADA ,ENCUESTA )
SELECT *
FROM OPENROWSET(
       'Microsoft.ACE.OLEDB.12.0',
       'Excel 12.0;Database=C:\REPORTES\CAMPANAS_IVR\REPORTE_LLAMADAS_BEEX.xlsx;HDR=YES',
       'SELECT * FROM [Sheet1$]')
WHERE NOT [FECHA Y HORA FIN] IS NULL AND [Tipo de marcación] = 'ivr'

; WITH CTE AS (
select lx.*,
ROW_NUMBER() OVER (PARTITION BY TELEFONO ORDER BY TIEMPO_HABLADO DESC)N
from #LLAMADAS_BEEX lx
)
DELETE CTE WHERE N>1

	   UPDATE LB
	   SET LB.DURACION = 
	   CAST('01/01/1900 '+
	   CONCAT(
				RIGHT('00'+CAST(DATEDIFF(SS,FECHA_INI, FECHA_FIN)/60/60 AS VARCHAR),2),
				':',
				RIGHT('00'+CAST((DATEDIFF(SS,FECHA_INI, FECHA_FIN)/60)-((DATEDIFF(SS,FECHA_INI, FECHA_FIN)/60/60)*60) AS varchar),2),
					':',
						RIGHT('00'+CAST(DATEDIFF(SS,FECHA_INI,FECHA_FIN)%60 AS VARCHAR),2)
			) AS datetime)
	   FROM #LLAMADAS_BEEX LB

	   SELECT * FROM #LLAMADAS_BEEX

--SELECT * FROM #IVR_BEEX



SELECT DE.COD_PRODUC, DE.COD_DEUDOR, I.* ,
             CASE WHEN STATUS_CALL = 'NO CONTESTADA' THEN 21
                    WHEN STATUS_CALL = 'OCUPADA' THEN 22
                    WHEN STATUS_CALL = 'Contestada' THEN 17
                    ELSE NULL END COD_CONTACT,
(SELECT TOP 1 DURACION FROM #LLAMADAS_BEEX LS WHERE I.TELEFONO = LS.TELEFONO) DURACION,
             ROW_NUMBER() OVER (PARTITION BY DE.COD_PRODUC, DE.COD_DEUDOR ORDER BY CASE WHEN STATUS_CALL = 'Contestada' THEN 1 WHEN STATUS_CALL = 'OCUPADA' THEN 2 ELSE 3 END ASC ) ID
INTO #DETALLE_MARCACIONES
FROM #IVR_BEEX I
JOIN BD_COBROS..DEUDOR De ON DE.NUM_CEDRUC = I.CODE_CLIENT
JOIN BD_COBROS..SITUACIO S ON S.COD_SITUAC = DE.COD_SITUAC AND S.SI_CTAVIG = 1
JOIN @TABLAPRODUCTOS T ON T.COD_PRODUC = DE.COD_PRODUC
WHERE DE.SI_RETIRA = 0 AND DE.MARCA = 'ADMINISTRATIVA'

--SELECT * FROM #DETALLE_MARCACIONES WHERE STATUS_CALL = 'FALLIDA' AND ID=1
DELETE FROM #DETALLE_MARCACIONES WHERE STATUS_CALL = 'FALLIDA' AND ID=1

--INSERTAR GESTIONES EN DIARIO ---

--INSERT INTO BD_COBROS..DIARIO (COD_PRODUC, COD_DEUDOR, FEC_GESTIO, COD_GESTIO, DES_GESTIO, DES_SEGUIM, FEC_SISTEM, USU_INGRES, USU_ULTMOD, FEC_ULTMOD, HOR_SISTEM,HORA_MOD, SI_GESTION, COD_CONTACT)
SELECT  DT.COD_PRODUC,
          DT.COD_DEUDOR,
          cast(convert(char(11), getdate(), 113) as datetime) AS FEC_GESTIO,
          'IVR' AS COD_GESTIO,
          'ENVIO DE CAMPAÑA IVR' AS DES_GESTIO,
          REPLACE(SUBSTRING(convert(varchar,SYSDATETIME()),1,10),'-','') + CASE WHEN DT.COD_CONTACT = 17 THEN 
          ' ESTIMADO CLIENTE, SU CUENTA VENCIDA CON BANCO DEL PACIFICO, HA SIDO TRASLADADA AL ESTUDIO JURÍDICO ROMERO Y ASOCIADOS PARA EL COBRO DEL VALOR PENDIENTE. 
		    LE PEDIMOS QUE SE PONGA AL DÍA INMEDIATAMENTE PARA EVITAR INTERESES Y CARGOS ADICIONALES. 
			LE RECORDAMOS ADEMÁS QUE, EN CASO DE NO PONERSE AL DÍA, SU CUENTA PODRÍA SER DEMANDADA CON UN PROCESO DE COACTIVA. COMUNÍQUESE A NUESTROS PBX (04) QUINIENTOS CUATROMIL, O AL (02) CINCOMIL CIENTOSESENTA. 
			SU PRONTA COMUNICACIÓN PERMITIRÁ ENCONTRAR JUNTOS LA MEJOR SOLUCIÓN.'
			ELSE ' SE MARCA AL CELULAR DEL CLIENTE, TIMBRA Y NO CONTESTA' END 
			AS DES_SEGIM,
         CONVERT(datetime,getdate(), 101) AS FEC_SYSTEM,
          824 AS USU_INGRES,
          824 AS USU_ULTMOD,
          CONVERT(datetime,FECHA_MARCACION, 101) AS FEC_ULTMOD,
          CONVERT(datetime,FECHA_MARCACION, 101)   AS HOR_SISTEM,
		  CONVERT(datetime,FECHA_MARCACION, 101)   AS HORA_MOD,
          1 AS SI_GESTION,
          DT.COD_CONTACT
          
 FROM #DETALLE_MARCACIONES DT 
 JOIN DEUDOR D ON D.COD_DEUDOR = DT.COD_DEUDOR AND D.COD_PRODUC = DT.COD_PRODUC
WHERE ID=1 AND FECHA_MARCACION <> '' AND D.MARCA = 'ADMINISTRATIVA'



                           --GUARDAR TELEFONOS EN MASIVOS
                           
                           /*
                           SELECT R.COD_PRODUC, R.COD_DEUDOR, R.COD_GESTIO, R.ID_REGISTRO, B.TELEFONO,
                                        'MSV.'+UPPER(STATUS_CALL) ESTADO, '000-'+U.COD_USUARI ORIGEN, SUBSTRING(CAST(newid() AS NVARCHAR(50)),1,30) UNIQUEID, 
										 CONVERT ( VARCHAR , DURACION, 108) DURACION, GETDATE() FECHA, CAST(NULL AS INT) ID_LLAMADA 
                           INTO #REGISTROS_ENVIO
                           FROM BD_COBROS..DIARIO R 
                           JOIN #DETALLE_MARCACIONES B ON B.COD_PRODUC = R.COD_PRODUC AND B.COD_DEUDOR = R.COD_DEUDOR
                           JOIN BD_COBROS..USUARIOS U ON U.NUM_USUARI = R.USU_ULTMOD
                           where r.fec_gestio = DATEADD(dd, DATEDIFF(dd,0, getdate()), 0) and r.cod_gestio in ('IVR')
                           and U.NUM_USUARI in(824) AND R.DES_GESTIO = 'ENVIO DE CAMPAÑA IVR'
                           
						   select * from #registros_envio
						   --DROP TABLE #REGISTROS_ENVIO
                           
                           INSERT INTO BD_REPORTES.[dbo].[fpb_tb_ReporteLlamadasSalientes] (UNIQUEID,ORIGEN,STARTTIME,STOPTIME,DESTINO,DURACION,ESTADO,FECHA)
                           SELECT UNIQUEID, ORIGEN, FECHA, FECHA, TELEFONO, CONVERT ( VARCHAR , DURACION, 108) DURACION,ESTADO, FECHA
                           FROM #REGISTROS_ENVIO D

                           INSERT INTO BD_REPORTES.[dbo].[fpb_tb_DiarioLlamadasSalientes] (UNIQUEID, ID_LLAMADA, ID_DIARIO, FECHA)
                           SELECT R.UNIQUEID, D.ID_LLAMADA,R.ID_REGISTRO, R.FECHA
                           FROM BD_REPORTES..[fpb_tb_ReporteLlamadasSalientes] D
                           JOIN #REGISTROS_ENVIO R ON R.UNIQUEID = D.UNIQUEID-- AND R.ID_LLAMADA = D.ID_LLAMADA
                           WHERE D.DESTINO = R.TELEFONO
                           

                           SELECT * FROM #DETALLE_MARCACIONES */

  /*
--- COMPROBAR CANTIDAD DE GESTIONES INGRESADAS.  
SELECT DISTINCT D.NUM_CEDRUC FROM BD_COBROS..DIARIO DI
JOIN @TABLAPRODUCTOS TP ON TP.COD_PRODUC = DI.COD_PRODUC 
JOIN DEUDOR D ON DI.COD_PRODUC = D.COD_PRODUC AND DI.COD_DEUDOR = D.COD_DEUDOR
WHERE DI.COD_GESTIO = 'IVR' AND DI.USU_INGRES = 824 AND DI.FEC_GESTIO = CAST(CONVERT(CHAR(11), GETDATE(), 113) AS DATETIME)
*/