/*
  INSTRUCCIONES PARA LA EJECUCION
  - EJECUTAR EN SERVIDOR 2 / OPERACIONES.
  - 
*/


USE BD_COBROS

DECLARE @FEC_CARGA DATETIME SET @FEC_CARGA = (SELECT CONVERT(VARCHAR(25),DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0),105));-- FECHA INICIO DE MES
--RANGO FECHAS MES ACTUAL
DECLARE @FECPM DATETIME SET @FECPM = DATEADD(DAY, 1 - DAY(@FEC_CARGA), @FEC_CARGA);
DECLARE @FECUL DATETIME SET @FECUL = EOMONTH(@FEC_CARGA);
--RANGO FECHAS MES ANTERIOR
DECLARE @FECPMA DATETIME SET @FECPMA = DATEADD(MONTH, -1, @FECPM);
DECLARE @FECULA DATETIME SET @FECULA = DATEADD(DAY, -1, @FECPM);


select 
	CASE WHEN a.COD_PRODUC=4 THEN 'VISA' ELSE 'MASTERCARD' END AS PRODUCTO,
	a.COD_PRODUC, a.COD_DEUDOR, d.NUM_PROOTR, d.NUM_CEDRUC, 
	a.[NOMBRE_CLIENTE ], 
	A.CAPITAL CAPI_INICIAL, A.TOTAL TOTAL_INICIAL,
	d.VAL_SALCAP, d.VAL_SALDO, D.VAL_PAGMIN, A.PV, d.FEC_SITUAC, 
	s.NOM_SITUAC,UB.NOM_UBICA AS CATEGORIA, DR.NOM_CATEGO AS DATO_RELEVANTE,
	U.NOM_USUARI AS EJECUT, G.GRUPO AS GRUP,
	CONVERT(VARCHAR(10),(SELECT MAX(FEC_PAGO) FROM BD_COBROS..PAGOS AS PA1 WHERE PA1.EST_PAGO = 3 AND PA1.COD_PRODUC = D.COD_PRODUC
    AND PA1.COD_DEUDOR = D.COD_DEUDOR), 103) AS ULT_PAG,
	(SELECT SUM(PP.VAL_DEPOSI) FROM BD_COBROS..PAGOS AS PP
		WHERE D.COD_PRODUC=PP.COD_PRODUC AND D.COD_DEUDOR=PP.COD_DEUDOR AND
		PP.EST_PAGO=3 AND PP.FEC_DEPOSI>=@FECPMA AND PP.FEC_DEPOSI<=@FECULA) AS PAG_MES_ANT,

	'NULL' GES_AB, 'NULL' GES_CBP, d.MARCA, D.MARCA2, d.MARCA_CAMPANIA
, 
	--convert(varchar(10),D.FEC_INGRES,103) as FEC_INGRES ,UB.NOM_UBICA AS UBICACION,
	--U.COD_USUARI AS EJECUT, G.GRUPO AS GRUP, G.GRUGEST, DR.NOM_CATEGO AS SUB_CATEGO,

	a.DESCRIPCION_ESTADO EST_MES_ACT,
	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' OBS_EJR,
	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' OBS_BANCO

INTO #BASE_CARTERAS_MES
from BD_CARTERAS..Asignaciones A 
left join BD_COBROS..DEUDOR d on d.COD_PRODUC=a.COD_PRODUC and d.COD_DEUDOR =a.COD_DEUDOR
       LEFT JOIN BD_COBROS..CATEGORI DR ON DR.COD_CATEGO = D.COD_CATEGO
       LEFT JOIN BD_COBROS..SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
       LEFT JOIN BD_COBROS..GRUPOS G ON G.NUM_USUARI = D.COD_EJECUT
       LEFT JOIN BD_COBROS..USUARIOS U ON U.NUM_USUARI = D.COD_EJECUT
       LEFT JOIN BD_COBROS..UBICADEU C ON C.COD_PRODUC = D.COD_PRODUC AND C.COD_DEUDOR = D.COD_DEUDOR
       LEFT JOIN BD_COBROS..UBICACIO UB ON UB.COD_UBICA = C.COD_UBICA
WHERE A.FECHA_CARGA BETWEEN @FECPMA AND @FECULA AND A.COD_PRODUC IN (4,19) AND D.MARCA = 'ADMINISTRATIVA'-- EXCLUYE CARTERA ADMINISTRATIVA
AND NOT EXISTS (SELECT * FROM BD_CARTERAS..Asignaciones A1
				WHERE A1.COD_PRODUC=A.COD_PRODUC AND A1.COD_DEUDOR=A.COD_DEUDOR
				AND D.MARCA = 'ADMINISTRATIVA' AND A1.FECHA_CARGA BETWEEN @FECPM AND @FECUL)
--SELECT * FROM #BASE_CARTERAS_MES

UPDATE A SET A.GES_AB = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR AND B.SI_GESTION=0 
        
UPDATE A SET A.GES_AB = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR AND B.SI_GESTION=0 
	AND COD_GESTIO<>'ZZ' AND COD_GESTIO<>'LD' AND COD_GESTIO<>'CN' AND COD_GESTIO<>'BD' AND COD_GESTIO<>'PL' AND COD_GESTIO<>'CV' AND COD_GESTIO<>'LIQ1' AND COD_GESTIO<>'CA1'

UPDATE A SET A.GES_CBP = B.COD_GESTIO 	FROM #BASE_CARTERAS_MES A, DIARIO B
	WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR
	AND COD_GESTIO IN ('CBP')

UPDATE A SET A.OBS_EJR='', OBS_BANCO=''  FROM #BASE_CARTERAS_MES A

UPDATE A SET A.PAG_MES_ANT=0.00 FROM #BASE_CARTERAS_MES A WHERE PAG_MES_ANT IS NULL


--- PARA REVISION DE SALDOS 

UPDATE A SET A.OBS_EJR = (CASE 
								WHEN GES_AB='PM' OR NOM_SITUAC = ('VERIF.SALDO(AC.CANC)') THEN 'CANCELADA'
								when NOM_SITUAC IN ('CUENTA CERRADA', 'LEGAL') then 'SITUACION NO CORRIENTE'
								when GRUP IS NULL then 'EJECUTIVO NO CORRIENTE'
								WHEN VAL_SALDO<=0 then 'SIN SALDO POR COBRAR'
								WHEN VAL_SALDO<10 THEN  'POSIBLE ENCERAMIENTO MENOR 10'
								ELSE '' END)
FROM #BASE_CARTERAS_MES A


-- TOTAL FALTANTES
SELECT PRODUCTO,	COD_PRODUC,	COD_DEUDOR,	NUM_PROOTR,	NUM_CEDRUC,	[NOMBRE_CLIENTE ], 	TOTAL_INICIAL,	VAL_SALCAP,
VAL_SALDO,	NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,	EJECUT,	GRUP,	ULT_PAG,	PAG_MES_ANT,
GES_AB,	GES_CBP,	EST_MES_ACT,	OBS_EJR,	OBS_BANCO
FROM #BASE_CARTERAS_MES

-- EJECUTAR PARA TODOS LOS FALTANTES
/*

--INSERTA MARCA DE RETIRO 
UPDATE D SET D.SI_RETIRA=1
--SELECT * 
FROM DEUDOR D
JOIN #BASE_CARTERAS_MES F ON D.COD_PRODUC=F.COD_PRODUC AND D.COD_DEUDOR=F.COD_DEUDOR
WHERE NOT NOM_SITUAC IN ('VERIF.SALDO(AC.CANC)', 'LEGAL', 'VERIFICAR SALDO(N/C)', 'LEGAL DEVUELTA','CUENTA CERRADA')

--INSERTA UNA GESTIÓN ZZ EN DIARIO

INSERT INTO BD_COBROS..DIARIO 
(COD_PRODUC,COD_DEUDOR,FEC_GESTIO,COD_GESTIO, FEC_SISTEM,DES_GESTIO,DES_SEGUIM, HOR_SISTEM,SI_GESTION,USU_INGRES,FEC_ULTMOD,USU_ULTMOD,HORA_MOD, COD_UBICA,SI_CATEGO,COD_CATEGO,COD_CONTACT)
	
SELECT COD_PRODUC,COD_DEUDOR,	DATEADD(DD, DATEDIFF(DD,0, GETDATE()), 0) FEC_GESTIO,
	'ZZ' COD_GESIO,	GETDATE() FEC_SISTEM, 	'CUENTA RETIRADA POR EL BANCO.' DES_GESTIO,	REPLACE(SUBSTRING(convert(VARCHAR,SYSDATETIME()),1,10),'-','')+
	' GESTIÓN AUTOMÁTICA CREADA POR EL SISTEMA, CUENTA SE ENCUENTRA EN ANÁLISIS Y REVISIÓN POR PARTE DEL ÁREA DE COBRANZAS DEBIDO AL RETIRO DE LA ASIGNACIÓN POR PARTE DE EL BANCO.' DES_SEGUIM,
	GETDATE() HOR_SISTEM,	1 SI_GESTION,	824 USU_INGRES,	GETDATE() FEC_ULTMOD,	824 USU_ULTMOD,	GETDATE() HORA_MOD,	0,0,0,0
FROM #BASE_CARTERAS_MES 
WHERE NOT NOM_SITUAC IN ('VERIF.SALDO(AC.CANC)', 'LEGAL', 'VERIFICAR SALDO(N/C)', 'LEGAL DEVUELTA','CUENTA CERRADA')

*/


-- A CONSULTAR COBRANZAS
SELECT PRODUCTO,	M.COD_PRODUC,	M.COD_DEUDOR,	M.NUM_PROOTR CIFCOD,	M.NUM_CEDRUC CEDULA,	[NOMBRE_CLIENTE ], TOTAL_INICIAL, M.VAL_SALCAP,
	   M.VAL_SALDO, NOM_SITUAC SITUACION, CATEGORIA,	DATO_RELEVANTE, M.MARCA ,CASE WHEN MARCA_JUICIO LIKE '%REES%' THEN 'REESTRUCTURACION'
			      WHEN MARCA_JUICIO LIKE '%NORMA%' THEN 'NORMAL'
				  WHEN MARCA_JUICIO LIKE '%DFP%'THEN 'DFP'
				  ELSE '' END [IND.REES.VGNTE],M.MARCA_CAMPANIA ESTADO, M.PV,EJECUT EJECUTIVO, GRUP GRUPO,D.MARCA2, ULT_PAG, PAG_MES_ANT,
	   GES_AB,	EST_MES_ACT,	OBS_EJR, OBS_BANCO
FROM #BASE_CARTERAS_MES M
JOIN BD_COBROS..DEUDOR D ON D.COD_PRODUC = M.COD_PRODUC AND D.COD_DEUDOR = M.COD_DEUDOR 
WHERE OBS_EJR IN ('', 'SIN SALDO POR COBRAR') AND D.MARCA_CAMPANIA = 'MADURADO'


-- CERRAR CUENTAS
SELECT PRODUCTO,	COD_PRODUC,	COD_DEUDOR,	NUM_PROOTR,	NUM_CEDRUC,	[NOMBRE_CLIENTE ], 	TOTAL_INICIAL,	VAL_SALCAP,
VAL_SALDO, PV, MARCA2 ,MARCA_CAMPANIA	,NOM_SITUAC,	CATEGORIA,	DATO_RELEVANTE,	EJECUT,	GRUP,	ULT_PAG,	PAG_MES_ANT,
GES_AB,	GES_CBP,	EST_MES_ACT,	OBS_EJR,	'CERRAR CUENTA' OBS_FINAL
INTO #CERRAR_CUENTAS
FROM #BASE_CARTERAS_MES WHERE NOT OBS_EJR IN ('','CANCELADA','SITUACION NO CORRIENTE', 'SIN SALDO POR COBRAR') OR MARCA_CAMPANIA <> 'MADURADO'

SELECT * FROM #CERRAR_CUENTAS

-- PARA EL CIERRE DE LAS CUENTAS
/*
BEGIN TRANSACTION
USE BD_COBROS
	DECLARE @MES VARCHAR(12) =UPPER(DATENAME(MONTH, GETDATE())) 
	DECLARE @COD_GESTIO VARCHAR(10),
	@NUM_USUARI SMALLINT
	SELECT  @COD_GESTIO='S7', -------- GESTIÓN PARA CERRAR CUENTAS.
	@NUM_USUARI = 824 -- USUARIO QUE EJECUTARA LA CONSULTA.

BEGIN TRY
BEGIN TRANSACTION CERRAR_S7

---***CIERRA GESTIONES ABIERTA***----
       UPDATE D
       SET D.DES_SEGUIM = CONVERT(varchar(8), GETDATE(), 112)+' FALTANTE ASIGNACION '+@MES+'. SE CIERRA CUENTA POR AUTORIZACIÓN DE COORDINADOR DE COBRANZAS, '+ T.OBS_FINAL+'.',
             D.SI_GESTION = 1 ,
             D.FEC_ULTMOD = GETDATE(),
             D.USU_ULTMOD = @NUM_USUARI, 
             D.HORA_MOD = GETDATE()
       FROM DIARIO D
       JOIN #CERRAR_CUENTAS T ON D.COD_PRODUC = T.COD_PRODUC       
       AND D.COD_DEUDOR = T.COD_DEUDOR 
       AND D.SI_GESTION = 0 --GESTION ABIERTA
     	 
---***CAMBIA LA SITUACIÓN ACTUAL A CERRADA***---
       UPDATE A
       SET A.COD_SITANT= A.COD_SITUAC,
             A.COD_SITUAC= G.COD_SITUAC,
             A.FEC_SITUAC= getdate()
       FROM DEUDOR A, #CERRAR_CUENTAS B, GESTION G
       WHERE A.COD_PRODUC=B.COD_PRODUC AND A.COD_DEUDOR=B.COD_DEUDOR
       AND G.COD_GESTIO=@COD_GESTIO

---***Crear un seguimiento de cuenta cerrada para las que no llegaron en cartera***---
       INSERT INTO DIARIO ( COD_PRODUC, COD_DEUDOR, FEC_GESTIO, DES_GESTIO, COD_GESTIO, COD_EJECUT, DES_SEGUIM, FEC_ULTMOD, HORA_MOD, SI_GESTION, USU_INGRES, FEC_SISTEM, USU_ULTMOD)
       SELECT D.COD_PRODUC, D.COD_DEUDOR, 
	   CONVERT(VARCHAR(10),GETDATE(),103) FEC_GESTIO, 
	   'SE CIERRA CUENTA' DES_GESTIO, 
	   @COD_GESTIO, 
	   D.COD_EJECUT, 
	   CONVERT(varchar(8), GETDATE(), 112)+' FALTANTE ASIGNACION '+@MES+'. SE CIERRA CUENTA POR AUTORIZACIÓN DE COORDINADOR DE COBRANZAS, '+ T.OBS_FINAL+'.'  DES_SEGUIM,
	   GETDATE() FEC_ULTMOD ,
	   GETDATE() HORA_MOD, 
	   1 SI_GESTION, 
	   @NUM_USUARI, 
	   GETDATE() FEC_SISTEM, 
	   @NUM_USUARI
       FROM #CERRAR_CUENTAS AS T, DEUDOR AS D
       WHERE D.COD_PRODUC=T.COD_PRODUC AND T.cod_deudor=D.cod_deudor AND D.COD_SITUAC=15; --->>>SITUACIÓN CERRADA

---***Insertar en HISTSITUAC los cambios realizados***---
       INSERT INTO HISTSITU (COD_PRODUC, COD_DEUDOR, COD_SITUAC, FEC_INGRES, HOR_INGRES, USU_INGRES)
       SELECT A.COD_PRODUC, A.COD_DEUDOR, 15, GETDATE(), GETDATE(), @NUM_USUARI
       FROM deudor AS a, #CERRAR_CUENTAS AS b
       WHERE a.cod_produc = B.cod_produc  and A.cod_deudor = B.cod_deudor

---***ERSU 20210729 MARCA COMO PROCESADAS LAS CAMPAÑAS PENDIENTES DE CUENTAS QUE SE CERRARON ***----
	   UPDATE P 
	   SET P.PROCESADO = 1,
	       P.SEGUIMIENTO = CONVERT(varchar(8), GETDATE(), 112)+' FALTANTE ASIGNACION '+@MES+'. SE CIERRA CUENTA POR AUTORIZACIÓN DE COORDINADOR DE COBRANZAS, '+ T.OBS_FINAL+'.',
		   P.FEC_SIST = GETDATE(),
		   P.HORA = GETDATE()
	   FROM PLANCAMPAÑAS P 
	   JOIN #CERRAR_CUENTAS T ON T.COD_PRODUC = P.COD_PRODUC AND T.COD_DEUDOR = P.COD_DEUDOR
	   WHERE P.PROCESADO = 0

	   COMMIT TRANSACTION CERRAR_S7
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE(), ERROR_NUMBER(), ERROR_SEVERITY()
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION CERRAR_S7
		END
	END CATCH 
	---***********CONSULTAR CUENTAS EN LAS QUE SE INSERTO LA GESTIÓN S7 PARA RESPALDO.***********---
--RESPALDO DE CIERRE
USE BD_COBROS
SELECT F.COD_PRODUC,F.COD_DEUDOR, DE.COD_SITUAC, S.NOM_SITUAC AS SITUACION, 
CASE WHEN DE.SI_RETIRA=1 THEN 'CON CHECK DE RETIRO' ELSE 'SIN_CHECK' END RETIRADA, D.COD_GESTIO, CONVERT(VARCHAR(10), D.FEC_GESTIO, 103) FEC_GESTIO , D.DES_GESTIO, D.DES_SEGUIM
FROM #CERRAR_CUENTAS F
JOIN DIARIO D ON D.COD_PRODUC=F.COD_PRODUC and D.COD_DEUDOR=F.COD_DEUDOR
JOIN DEUDOR DE ON F.COD_PRODUC=DE.COD_PRODUC AND F.COD_DEUDOR=DE.COD_DEUDOR
JOIN SITUACIO S ON DE.COD_SITUAC=S.COD_SITUAC
where D.FEC_GESTIO>= GETDATE()-1 and D.COD_GESTIO='S7'

--DROP TABLE #BASE_CARTERAS

 --CONFIRMAR TRASACCION--
	--COMMIT TRANSACTION;

-- REVERTIR TRASACCION--
	--ROLLBACK TRANSACTION;

*/

/*
SELECT S.NOM_SITUAC,* FROM DEUDOR D
JOIN #CERRAR_CUENTAS C ON D.COD_PRODUC = C.COD_PRODUC AND D.COD_DEUDOR = C.COD_DEUDOR
JOIN SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
*/