USE BD_COBROS;

DECLARE @FECHA DATETIME SET @FECHA = '01-06-2025'-- COLOCAR FECHA SOLO INICIO DE CADA MES
DECLARE @FECPM DATETIME SET @FECPM = (SELECT CONVERT(VARCHAR(25),DATEADD(DD,-(DAY(@FECHA)-1),@FECHA),105))
DECLARE @FECUL DATETIME SET @FECUL = (SELECT CONVERT(VARCHAR(25),DATEADD(DD,-(DAY(DATEADD(MM,1,@FECHA))),DATEADD(MM,1,@FECHA)),105))

CREATE TABLE #DETALLE
(      COD_ABOGADO VARCHAR(10),
       TARJETA VARCHAR(100),
       CIFCOD VARCHAR(100),
       CEDULA VARCHAR(25),
       NOMBRES VARCHAR(250),
       VALOR_PAGADO DECIMAL(18,2),
       FECHA_PAGO VARCHAR(250),
       VALOR_PROTESTO DECIMAL(18,2),
       FECHA_PROTESTO VARCHAR(250),
       VALOR_NETO DECIMAL(18,2),
       DIAS_VENCIDOS INT,
       FECHA_TRASLADO VARCHAR(250), 
       DIAS_LEGAL INT,
       TARIFA INT,
       HONORARIO_PAGAR DECIMAL	(18,2)
)

INSERT INTO #DETALLE
SELECT 'LRR' COD_ABOGADO, CIFCOD_CLIENTE TARJETA,CIFCOD_CLIENTE CIFCOD, IDENTIFICACION_CLIENTE_TITULAR CEDULA, [Nombre Completo] NOMBRES, 
       VALOR_TRANSACCION_TOTAL VALOR_PAGADO, 
       FECHA_PROCESO FECHA_PAGO, 0 VALOR_PROTESTO, 0 FECHA_PROTESTO, VALOR_TRANSACCION_TOTAL VALOR_NETO, 0 DIAS_VENCIDOS, 
	   0 FECHA_TRASLADO, 0 DIAS_LEGAL, 0 TARIFA, 0 HONORARIO_PAGAR 
FROM OPENROWSET(
       'Microsoft.ACE.OLEDB.12.0',
       'Excel 12.0;Database=C:\reportes\ARCHIVOS_PAGOS\PLANTILLAPAG_PACIFICO_ADMI.xlsx;HDR=YES',
       'SELECT * FROM [Sheet 1$]')

SELECT * FROM #DETALLE

update  #DETALLE set FECHA_PAGO = null where FECHA_PAGO = '0'
update  #DETALLE set FECHA_PROTESTO = null where FECHA_PROTESTO ='0'
update  #DETALLE set FECHA_TRASLADO = null where FECHA_TRASLADO ='0'

-- ==========================================================
-- PARA INGRESO DE PAGOS ADICIONALES DEL MES (CONSULTAS COB)
-- ==========================================================
INSERT INTO #DETALLE SELECT 'G01','F76291','F76291',NULL,NULL,50.00,'20250602',0,NULL,50.00,0,NULL,0,0,0;
INSERT INTO #DETALLE SELECT 'G01','431545','431545',NULL,NULL,300.00,'20250602',0,NULL,300.00,0,NULL,0,0,0;
INSERT INTO #DETALLE SELECT 'G01','N55322','N55322',NULL,NULL,100.00,'20250602',0,NULL,100.00,0,NULL,0,0,0;
INSERT INTO #DETALLE SELECT 'G01','A38212','A38212',NULL,NULL,240.00,'20250602',0,NULL,240.00,0,NULL,0,0,0;
INSERT INTO #DETALLE SELECT 'G01','H47341','H47341',NULL,NULL,100.00,'20250602',0,NULL,100.00,0,NULL,0,0,0;
--INSERT INTO #DETALLE SELECT 'G01','J27862','J27862',NULL,NULL,80.00,'20241202',0,NULL,80.00,0,NULL,0,0,0;
--INSERT INTO #DETALLE SELECT 'G01','G79999','G79999',NULL,NULL,125.00,'20241212',0,NULL,125.00,0,NULL,0,0,0;

-- ==========================================================
-- [1] PAGOS EN COBROS NO REPORTADOS EN LISTADOS
-- ==========================================================
SELECT 'G01', NUM_PRODUC, NUM_PROOTR, 0, 0, PP.VAL_PAGO, PP.FEC_DEPOSI ,0,null,0,0,null,0,0,0 FROM PAGOS PP 
LEFT JOIN DEUDOR D ON D.COD_PRODUC=PP.COD_PRODUC AND D.COD_DEUDOR=PP.COD_DEUDOR
WHERE PP.EST_PAGO = 3 AND PP.FEC_DEPOSI BETWEEN @FECPM AND @FECUL
AND PP.COD_PRODUC IN (4,19) AND MARCA = 'ADMINISTRATIVA'
AND NOT EXISTS (SELECT * FROM #DETALLE DE WHERE D.NUM_PROOTR = DE.CIFCOD)


-- ==========================================================
-- [2] DETALLE GENERAL DE PAGOS
-- ==========================================================

SELECT DP.COD_ABOGADO, DP.TARJETA, DP.CIFCOD, DP.CEDULA, DP.NOMBRES, DP.VALOR_PAGADO, 
             CONVERT(DATETIME,DP.FECHA_PAGO)FECHA_PAGO, DP.VALOR_PROTESTO,CONVERT(DATETIME,DP.FECHA_PROTESTO)FECHA_PROTESTO, 
             DP.VALOR_NETO, DP.DIAS_VENCIDOS, CONVERT(DATETIME,DP.FECHA_TRASLADO)FECHA_TRASLADO, DP.DIAS_LEGAL, DP.TARIFA, DP.HONORARIO_PAGAR, 		 
			 D.NUM_PRODUC, D.COD_PRODUC, D.COD_DEUDOR, U.NOM_USUARI ,G.GRUPO,S.NOM_SITUAC,D.MARCA_CAMPANIA, 
			 CASE WHEN MARCA_JUICIO LIKE '%REES%' THEN 'REESTRUCTURACION'
			      WHEN MARCA_JUICIO LIKE '%NORMA%' THEN 'NORMAL'
				  WHEN MARCA_JUICIO LIKE '%DFP%'THEN 'DFP'
				  ELSE '' END [IND.REES.VGNTE], D.VAL_PAGMIN,
			 (SELECT SUM(PP.VALOR_PAGADO) FROM #DETALLE AS PP WHERE DP.CIFCOD=PP.CIFCOD) AS PAGADO_UNI,
			 (SELECT SUM(PP.VALOR_PROTESTO) FROM #DETALLE AS PP WHERE DP.CIFCOD=PP.CIFCOD) AS PROTESTO_UNI,
			 (
			 SELECT SUM(PP.VAL_PAGO) FROM PAGOS PP 
				LEFT JOIN DEUDOR DE ON DE.COD_PRODUC=PP.COD_PRODUC AND PP.COD_DEUDOR=DE.COD_DEUDOR 
				where PP.EST_PAGO=3 and PP.FEC_DEPOSI between @FECPM AND @FECUL AND DE.COD_PRODUC IN (4,19)
				AND DP.CIFCOD=DE.NUM_PROOTR
			 ) AS PAGADO_COB, VALOR_PAGADO AS DIFERENCIA, 
			 D.SI_RETIRA AS RETIRADA, 
			 CASE WHEN (SELECT 1 FROM BD_CARTERAS..ASIGNACIONES A 
						WHERE A.COD_PRODUC = D.COD_PRODUC AND A.COD_DEUDOR = D.COD_DEUDOR 
						AND A.FECHA_CARGA >= @FECHA AND A.DESCRIPCION_ESTADO = 'ADMINISTRATIVA' ) = 1 THEN 'SI' ELSE 'NO' END ASIGNADA,
			 OBSER='SIN OBSERVACIONES REALIZADAS' 
			 
INTO #ANALISIS_PAGOS
FROM #DETALLE DP
LEFT JOIN DEUDOR D ON D.NUM_PROOTR=DP.CIFCOD AND D.COD_PRODUC IN (4,19)
LEFT JOIN SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
LEFT JOIN GRUPOS G ON G.NUM_USUARI = D.COD_EJECUT
LEFT JOIN USUARIOS U ON U.NUM_USUARI = D.COD_EJECUT

UPDATE #ANALISIS_PAGOS set PAGADO_COB = 0 where PAGADO_COB IS NULL

UPDATE A SET A.DIFERENCIA = (A.PAGADO_UNI-A.PROTESTO_UNI)-A.PAGADO_COB
FROM #ANALISIS_PAGOS A

UPDATE A SET OBSER='YA INGRESADO'
FROM #ANALISIS_PAGOS A WHERE DIFERENCIA = 0

UPDATE A SET OBSER='YA INGRESADO - ADICIONAL'
FROM #ANALISIS_PAGOS A WHERE DIFERENCIA = 0 AND COD_ABOGADO='G00'

UPDATE A SET OBSER='REVISAR - PAGO ING SUP.'
FROM #ANALISIS_PAGOS A WHERE DIFERENCIA < 0

UPDATE A SET OBSER='INGRESAR'
FROM #ANALISIS_PAGOS A WHERE DIFERENCIA > 0

UPDATE A SET OBSER = 'NO INGRESAR - NO ASIGNADA' 
FROM #ANALISIS_PAGOS A WHERE ASIGNADA = 'NO'

SELECT * FROM #ANALISIS_PAGOS


-- ==========================================================
-- [3] PAGOS A INGRESAR
-- ==========================================================
SELECT NUM_PRODUC, CONVERT(VARCHAR(10),MAX(FECHA_PAGO), 103) AS FECHA, DIFERENCIA AS VALOR, TIPO='EF',
COD_PRODUC, COD_DEUDOR, '779' USU_INGRES ,OBSER
FROM #ANALISIS_PAGOS
WHERE OBSER = 'INGRESAR' 
GROUP BY NUM_PRODUC,DIFERENCIA,COD_PRODUC,COD_DEUDOR,OBSER


-- ==========================================================
-- [4] PAGOS CON DIFERENCIAS (MAYOR EN COBROS)
-- ==========================================================
SELECT COD_PRODUC, COD_DEUDOR, NUM_PRODUC, CEDULA,
NOMBRES, FECHA_PAGO, PAGADO_UNI, PROTESTO_UNI,FECHA_PROTESTO,
PAGADO_COB, DIFERENCIA, NOM_USUARI AS EJECUTIVO, CIFCOD, OBSER
FROM #ANALISIS_PAGOS
WHERE OBSER = 'REVISAR - PAGO ING SUP.'

-- ==========================================================
-- [5] VERIFICACION DE RECUPERACION
-- ==========================================================

DECLARE @FECHA2 DATETIME SET @FECHA2 = '01/06/2025' --MODIFICAR SOLO INICIO DE MES
DECLARE @FECPM2 DATETIME SET @FECPM2 = (SELECT CONVERT(VARCHAR(25),DATEADD(DD,-(DAY(@FECHA2)-1),@FECHA2),105))
DECLARE @FECUL2 DATETIME SET @FECUL2 = (SELECT CONVERT(VARCHAR(25),DATEADD(DD,-(DAY(DATEADD(MM,1,@FECHA2))),DATEADD(MM,1,@FECHA2)),105))

UPDATE A SET COD_ABOGADO = 'G10' FROM #DETALLE A
SELECT 
	DE.COD_ABOGADO,
	(SELECT SUM(PP.VALOR_PAGADO) FROM #DETALLE PP) - (SELECT SUM(PP.VALOR_PROTESTO) FROM #DETALLE PP)
		AS REPORTE_BANCO,
	(SELECT SUM(PP.VAL_PAGO) FROM PAGOS PP 
	JOIN DEUDOR R ON R.COD_PRODUC = PP.COD_PRODUC AND R.COD_DEUDOR = PP.COD_DEUDOR
		WHERE PP.EST_PAGO = 3 and PP.FEC_DEPOSI between @FECPM2 AND @FECUL2 AND PP.COD_PRODUC IN (4,19) AND R.MARCA = 'ADMINISTRATIVA') AS SIS_COBROS,
	(SELECT SUM(PP.VALOR_PAGADO) FROM #DETALLE PP) - (SELECT SUM(PP.VALOR_PROTESTO) FROM #DETALLE PP)
	- (SELECT SUM(PP.VAL_PAGO) FROM PAGOS PP 
	JOIN DEUDOR R ON R.COD_PRODUC = PP.COD_PRODUC AND R.COD_DEUDOR = PP.COD_DEUDOR
		WHERE PP.EST_PAGO = 3 and PP.FEC_DEPOSI between @FECPM2 AND @FECUL2 AND PP.COD_PRODUC IN (4,19) AND R.MARCA = 'ADMINISTRATIVA') AS DIFERENCIA 
	FROM #DETALLE DE
	GROUP BY DE.COD_ABOGADO;

-- =================================================================
-- [6] POSTERIOR AL INGRESO DE PAGOS: PAGOS DE EJECUTIVO NO VIGENTE
-- =================================================================

/*
SELECT
CASE WHEN D.COD_PRODUC = 4 THEN 'VISA BCO. DEL PACIFICO' ELSE 'MASTERCARD' END AS PRODUCTO, P.COD_DEUDOR,
P.NOMBRES, CONVERT(VARCHAR(10),P.FECHA_PAGO, 103) AS FECHA_PAGO, P.DIFERENCIA AS VALOR, D.MARCA, D.MARCA2, 
ISNULL(D.MARCA_CAMPANIA,'') MARCA_CAMPANIA, CASE WHEN MARCA_JUICIO LIKE '%REES%' THEN 'REESTRUCTURACION'
			      WHEN MARCA_JUICIO LIKE '%NORMA%' THEN 'NORMAL'
				  WHEN MARCA_JUICIO LIKE '%DFP%'THEN 'DFP'
				  ELSE '' END [IND.REES.VGNTE], D.PV, D.VAL_SALCAP, D.VAL_SALDO, P.NOM_SITUAC AS SITUACION, P.NOM_USUARI AS EJECUTIVO, UB.NOM_UBICA AS CATEGORIA,
CASE WHEN P.DIFERENCIA < 20 AND D.VAL_SALDO > 0 THEN 'NO'
     WHEN D.MARCA_CAMPANIA = 'RECUPERADO' --OR VALOR_PAGADO >= (D.VAL_PAGMIN-20) 
	 THEN 'NO'
	   ELSE 'SI'
	  END AS ASIGNAR, W.NOM_USUARI NUEVO_EJECUTIVO, 
D.COD_PRODUC, D.COD_DEUDOR, D.NUM_CEDRUC, D.NUM_PRODUC, D.MARCA,
D.VAL_SALDO, D.COD_EJECUT, 'ILOC' TIPO
FROM #ANALISIS_PAGOS P
LEFT JOIN DEUDOR D ON D.NUM_PROOTR = P.CIFCOD AND D.COD_PRODUC IN (4,19) 
LEFT JOIN UBICADEU C ON C.COD_PRODUC = D.COD_PRODUC AND C.COD_DEUDOR = D.COD_DEUDOR
LEFT JOIN UBICACIO UB ON UB.COD_UBICA = C.COD_UBICA
JOIN USUARIOS W ON W.NUM_USUARI = D.COD_EJECUT
WHERE OBSER = 'INGRESAR' AND GRUPO IS NULL
AND P.FECHA_PAGO = (SELECT MAX(PP.FECHA_PAGO) FECHA
					FROM #ANALISIS_PAGOS PP
					WHERE PP.COD_PRODUC = D.COD_PRODUC
					AND PP.COD_DEUDOR = D.COD_DEUDOR)

ORDER BY ASIGNAR DESC, D.VAL_SALDO DESC, P.DIFERENCIA DESC, D.COD_PRODUC

-- =================================================================
-- [7] POSTERIOR AL INGRESO DE PAGOS: PAGOS DE SITUACION NO VIGENTE
-- =================================================================

SELECT 
CASE WHEN D.COD_PRODUC = 4 THEN 'VISA BCO. DEL PACIFICO' ELSE 'MASTERCARD' END AS PRODUCTO, P.COD_DEUDOR,
P.NOMBRES, CONVERT(VARCHAR(10),MAX(P.FECHA_PAGO), 103) AS FECHA_PAGO, P.DIFERENCIA AS VALOR,
P.NOM_SITUAC AS SITUACION, P.NOM_USUARI AS EJECUTIVO, UB.NOM_UBICA AS CATEGORIA, D.MARCA,
ISNULL(D.MARCA_CAMPANIA,'') MARCA_CAMPANIA, D.VAL_SALCAP, D.VAL_SALDO
FROM #ANALISIS_PAGOS P
LEFT JOIN DEUDOR D ON D.NUM_PROOTR = P.CIFCOD AND D.COD_PRODUC IN (4,19)
LEFT JOIN SITUACIO S ON S.COD_SITUAC = D.COD_SITUAC
LEFT JOIN UBICADEU C ON C.COD_PRODUC = D.COD_PRODUC AND C.COD_DEUDOR = D.COD_DEUDOR
LEFT JOIN UBICACIO UB ON UB.COD_UBICA = C.COD_UBICA
WHERE OBSER = 'INGRESAR' AND S.COD_SITUAC IN (5,6,15)
GROUP BY P.FECHA_PAGO, D.COD_PRODUC, P.COD_DEUDOR, P.NOMBRES, P.DIFERENCIA, P.NOM_SITUAC,
P.NOM_USUARI, D.VAL_SALCAP, D.VAL_SALDO, UB.NOM_UBICA, D.MARCA, D.MARCA_CAMPANIA;


-- =================================================================
-- [8] POSTERIOR AL INGRESO DE PAGOS: PAGOS PROTESTADOS
-- =================================================================

SELECT DISTINCT
CASE WHEN COD_PRODUC = 4 THEN 'VISA BCO. DEL PACIFICO' ELSE 'MASTERCARD' END AS PRODUCTO, NOM_USUARI EJECUTIVO,
COD_DEUDOR, NOMBRES, 
(SELECT MAX(FECHA_PAGO) FROM #ANALISIS_PAGOS A 
WHERE A.COD_PRODUC = B.COD_PRODUC AND A.COD_DEUDOR = B.COD_DEUDOR AND FECHA_PAGO IS NOT NULL) FECHA_PAGO,
PAGADO_UNI VALOR,
(SELECT DISTINCT FECHA_PROTESTO FROM #ANALISIS_PAGOS A 
WHERE A.COD_PRODUC = B.COD_PRODUC AND A.COD_DEUDOR = B.COD_DEUDOR AND FECHA_PROTESTO IS NOT NULL) FECHA_PROTESTO,
PROTESTO_UNI VALOR_PROTESTO,
DIFERENCIA VALOR_NETO
FROM #ANALISIS_PAGOS B
WHERE OBSER = 'REVISAR - PAGO ING SUP.'

*/