USE BD_COBROS;


SELECT * 
INTO #BASE_EMAIL
FROM OPENROWSET(
    'Microsoft.ACE.OLEDB.12.0',
    'Excel 12.0;Database=C:\REPORTES\PROCESOS_MAPI\BLOCKS.xlsx;HDR=YES',
    'SELECT * FROM [Hoja1$]'
);


WITH TBL_CODE_ERROR AS (
    SELECT 
        CASE 
            WHEN STATUS_MAIL = '5.2.2' AND MAIL2 IS NOT NULL THEN 'BANDEJA LLENA'
            WHEN REASON LIKE '%554 5.2.2 mailbox full; S%' THEN 'BANDEJA LLENA'
            WHEN STATUS_MAIL = '5.2.2' AND MAIL2 IS NULL THEN 'BANDEJA LLENA'
            WHEN STATUS_MAIL = '4.2.2' THEN 'BANDEJA LLENA'

            WHEN STATUS_MAIL IN ('5.7.1', '451', '4.1.8') AND MAIL2 IS NULL THEN 'ANTI-SPAM'
            WHEN STATUS_MAIL = '5.7.1' THEN 'ANTI-SPAM'
            WHEN STATUS_MAIL = '550' THEN 'ANTI-SPAM'
            WHEN STATUS_MAIL = '5.4.14' THEN 'ANTI-SPAM'
            WHEN STATUS_MAIL IN ('5.5.1','5.4.1','4.4.4') THEN 'ANTI-SPAM'
            WHEN STATUS_MAIL = '4.7.1' THEN 'ANTI-SPAM'

            WHEN STATUS_MAIL IS NULL AND (REASON LIKE '%UNABLE%' OR REASON LIKE '%421%') THEN 'NO EXISTE / INCORRECTO O INVALIDO'
            WHEN STATUS_MAIL IS NULL AND REASON LIKE '%ERROR DIALING%' THEN 'NO EXISTE / INCORRECTO O INVALIDO'
            WHEN STATUS_MAIL IS NULL AND REASON LIKE '%invalid address%' THEN 'NO EXISTE / INCORRECTO O INVALIDO'
            WHEN STATUS_MAIL IN ('5.1.1','5.5.0','554','552','5.2.1','5.0.0') THEN 'NO EXISTE / INCORRECTO O INVALIDO'
        END AS ERROR_CODE,
        COALESCE(MAIL2, EMAIL, CREATED) AS EMAIL_CLASIFICADO
    FROM #BASE_EMAIL
)

SELECT DISTINCT ERROR_CODE AS STATUS_MAIL, EMAIL_CLASIFICADO AS EMAIL
INTO #INMAIL
FROM TBL_CODE_ERROR
WHERE ERROR_CODE IS NOT NULL

-- ELIMINAR REGISTROS QUE SI COINCIDIERON CON LOS CODIGOS DE ERROR CONTEMPLADOS
DELETE B
FROM #BASE_EMAIL B
JOIN #INMAIL I ON COALESCE(B.MAIL2, B.EMAIL, B.CREATED) = I.EMAIL


SELECT * FROM #BASE_EMAIL -- CODIGOS NO ENCONTRADOS

-- ANALISIS DE ERRORES
SELECT DISTINCT EMAIL, STATUS_MAIL, GETDATE() AS FECHA_REPORTE 
INTO #RESULT
FROM #INMAIL
ORDER BY STATUS_MAIL DESC

SELECT * FROM #RESULT

DROP TABLE #INMAIL
DROP TABLE #BASE_EMAIL
DROP TABLE #RESULT